### ISSUE TITLE
Access to SQL console

### ISSUE THREAD

**Issue by joneslee85** [lotus/lotus#123]
**Status:** In Progress

Provide a convenient way to access the SQL console. The feature should resemble the Rails's `rake db:console`

The interface for the CLI would be: `bundle exec lotus dbconsole`. The command should look into the configuration of adapter which is set in `lib/<app_name>.rb`.

Please be noted that the command only works if adapter is SQL, it should raise error or warning that if it uses non-SQL adapter.

**Comment by Linuus** [comment]
I'd like to give this a shot if that is OK :)

**Comment by jodosha** [comment]
@Linuus @joneslee85 I'd say to start simple with this and support only the database used in `lib/`.

The data that you need is the type of database and a connection string. So I was thinking if it may be worth to read it from the dotenv files, without introspecting Lotus::Model.

When you create an application with `lotus new bookshelf`, the CLI creates some files under `config/`.
The database configuration is named after the application (eg. `BOOKSHELF_DATABASE_URL`).

What if we generate it only with `DATABASE_URL` so this command just need to lookup that env var and start a database REPL?

Thoughts?

**Comment by AlfonsoUceda** [comment]
@jodosha Imagine you have two lotus applications in the same machine, an they are using the same `DATABASE_URL`, will it be a problem with this?

**Comment by jodosha** [comment]
@AlfonsoUceda good point. :+1: 

I suggest to generate a `.lotusrc` file with those preferences:

```
application_name: bookshelf
```

So it will be able to compose the dynamic part from that configuration and concat with `ENV["#{ application_name.upcase }_DATABASE_URL"]`.

This can be useful for code generators too.

**Comment by AlfonsoUceda** [comment]
:+1:

**Comment by jodosha** [comment]
The only downside of bypassing the adapter is to maintain here the logic that passes the right args to the different database CLIs.

Probably the adapter should indicate the right string to start the REPL.

**Comment by Linuus** [comment]
@jodosha So when generating a new Lotus app we should create a .lotusrc file and put the app name in there in yml format? Then read this in the dbconsole command and find the correct env variable.

Why not pass in the app name to the command?
`lotus dbconsole bookshelf` <-- Connects to BOOKSHELF_DATABASE_URL
`lotus dbconsole web` <-- Connects to the WEB_DATABASE_URL

**Comment by jodosha** [comment]
@Linuus That could be an alternative. But again, I'm thinking if it's better to let the adapters to return the CLI connection string.

```ruby
adapter.connection_string # => "psql -h localhost" etc.
adapter.connection_string # => "mysql -h localhost" etc.
```

It this way an adapter author will implement that method and we can hook `lotus dbconsole` with that output.

```ruby
adapter.connection_string # => "redis ..."
```

If we don't apply this strategy, we're forced to maintain all those connections strings here in `lotusrb`, which doesn't seems to be the best way to go.

I suggest to do:

```shell
lotus dbconsole # loads main adapter from lib/ (Lotus::Model.configuration.adapter)
lotus dbconsole web # Web::Model.configuration.adapter
```

**Comment by Linuus** [comment]
@jodosha Yes I agree with that. I looked at Rails console command and it is messy because they do all that stuff in there.


 I'll give this a go during the weekend! :)

**Comment by jodosha** [comment]
I'm only concerned about security: this command needs to trust that the returned REPL command isn't evil, in case if third party adapters.

http://lucaguidi.com

**Comment by joneslee85** [comment]
@Linuus thanks for your offer, however @unrealhoang has been working on this feature as per https://github.com/lotus/lotus/pull/126. Can you please chat to @unrealhoang on chat room to see if he is happy to let you take over?

@jodosha I am feeling uneasy with the approach reading from dotenv ENV vars, firstly there is no _hard_ convention on the naming of these var, user can change the naming of ENV. Secondly, these dotenv files aren't to be deployed to production anyway, thus there is extra work to make it read ENV vars directly on production. Thirdly, it is hard to tell from the dotenv var if the adapter is truly SQL or not.

Thus, I propose that we should stick to the approach of reading from adapter configuration like I proposed before.

**Comment by Linuus** [comment]
@jodosha @joneslee85 Where did we land regarding letting the adapter specify the command to run the actual console?

There are two options as discussed above.

1. Add the logic of figuring out the adapter type and command to run in the dbconsole command. (Safer, but we need to maintain it).
2. Add a new interface to the adapter where the adapter developer adds a method returning the command to run and we just execute it. (Less safe, easier to maintain).

Option 2 seems more logical to me. Any ideas on how to avoid the security issues?

**Comment by Linuus** [comment]
To have something to discuss around I have made a quick take on this. This requires changes to Lotus::Model as well to add the `adapter.connection_string` @jodosha was talking about above. It is not a complete PR yet but here are the relevant commits.

Changes to Lotus::Model:
https://github.com/Linuus/model/commit/cff00271152d5382285e00be8136c7edaf848a31

Changes to Lotus:
https://github.com/Linuus/lotus/commit/b0cf5702e5d965dd2c41def08d1aeabbb100d30f

Any thoughts? Should I clean it up and make a PR? Should we take another approach all together?

**Comment by joneslee85** [comment]
@Linuus looks good. I like it. Please clean up and make a PR. Much  thanks

**Comment by Linuus** [comment]
@joneslee85 Great, thanks for the feedback!

**Comment by joneslee85** [comment]
@Linuus wondering if you need any help on this?

**Comment by Linuus** [comment]
@joneslee85 Not at the moment. I have just had a lot to do at work lately. I am not really sure how to test the CLI part but I'll have a look at the other tests and see if I can figure it out. Otherwise I'll send you a message :)
