### ISSUE TITLE
Dotenv error when application name includes a dash

### ISSUE THREAD

**Issue by robyurkowski** [lotus/lotus#129]
When I create an application with a dash in its name, running `bundle exec lotus server` fails even when I've not changed anything. 

I can reproduce this on both the latest gem version and when generated using `--lotus-head`.

I suspect we need to do some sanitization of app names to prevent invalid characters from being used in `ENV` variables.

Here's an example stack trace:

    /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/gems/dotenv-1.0.2/lib/dotenv/parser.rb:59:in `block in call': Line "ROB-DYN_DATABASE_URL=\"file:///db/rob-dyn_development\"" doesn't match format (Dotenv::FormatError)
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/gems/dotenv-1.0.2/lib/dotenv/parser.rb:37:in `each'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/gems/dotenv-1.0.2/lib/dotenv/parser.rb:37:in `inject'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/gems/dotenv-1.0.2/lib/dotenv/parser.rb:37:in `call'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/gems/dotenv-1.0.2/lib/dotenv/parser.rb:29:in `call'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/gems/dotenv-1.0.2/lib/dotenv/environment.rb:10:in `load'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/gems/dotenv-1.0.2/lib/dotenv/environment.rb:6:in `initialize'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/gems/dotenv-1.0.2/lib/dotenv.rb:16:in `new'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/gems/dotenv-1.0.2/lib/dotenv.rb:16:in `block in overload'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/gems/dotenv-1.0.2/lib/dotenv.rb:27:in `call'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/gems/dotenv-1.0.2/lib/dotenv.rb:27:in `block (2 levels) in with'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/gems/dotenv-1.0.2/lib/dotenv.rb:26:in `each'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/gems/dotenv-1.0.2/lib/dotenv.rb:26:in `block in with'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/gems/dotenv-1.0.2/lib/dotenv.rb:25:in `tap'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/gems/dotenv-1.0.2/lib/dotenv.rb:25:in `with'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/gems/dotenv-1.0.2/lib/dotenv.rb:16:in `overload'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/bundler/gems/lotus-9e7ec45d7765/lib/lotus/environment.rb:368:in `set_application_env_vars!'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/bundler/gems/lotus-9e7ec45d7765/lib/lotus/environment.rb:353:in `set_env_vars!'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/bundler/gems/lotus-9e7ec45d7765/lib/lotus/environment.rb:160:in `block in initialize'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/bundler/gems/lotus-9e7ec45d7765/lib/lotus/environment.rb:160:in `synchronize'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/bundler/gems/lotus-9e7ec45d7765/lib/lotus/environment.rb:160:in `initialize'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/bundler/gems/lotus-9e7ec45d7765/lib/lotus/cli.rb:82:in `new'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/bundler/gems/lotus-9e7ec45d7765/lib/lotus/cli.rb:82:in `environment'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/bundler/gems/lotus-9e7ec45d7765/lib/lotus/cli.rb:32:in `server'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/bundler/gems/lotus-9e7ec45d7765/bin/lotus:4:in `<top (required)>'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/bin/lotus:23:in `load'
        from /home/rob/Sites/r/rob-dyn/vendor/gems/ruby/2.1.0/bin/lotus:23:in `<main>'

**Comment by joneslee85** [comment]
`When I create an application with a dash in its name` - can you please let me know which command did you use?

**Comment by robyurkowski** [comment]
In the former case, `bundle exec lotus new rob-dyn` and then `bundle exec lotus new rob-dyn --lotus-head`.

**Comment by joneslee85** [comment]
@robyurkowski this is a straight-forward and easy issue, would you be able to submit a PR for this?

**Comment by jodosha** [comment]
@robyurkowski Thanks for reporting this.

Reference: http://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap08.html

> Environment variable names [...] consist solely of uppercase letters, digits, and the '_' (underscore).

**Comment by robyurkowski** [comment]
I will, the next bit of free time I get.

On Friday, January 9, 2015, Trung Lê <notifications@github.com> wrote:

> @robyurkowski <https://github.com/robyurkowski> this is a
> straight-forward and easy issue, would you be able to submit a PR for this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lotus/lotus/issues/129#issuecomment-69330020>.
>


-- 
*Rob Yurkowski*
Freelance Web Developer
rob@yurkowski.net | @robyurkowski <https://www.twitter.com/robyurkowski> |
519 . 379 . 3940

**Comment by jodosha** [comment]
@robyurkowski If you're going to write a fix for this. May I ask you to forbid the name `lotus` for an application?

```shell
% lotus new lotus
Reserved name blah blah..
```

It should be avoided, because we create modules when the application starts and having `Lotus` as top module for an application creates clashes with the modules from the form.

**Comment by robyurkowski** [comment]
Happy to, but I think I'll do it in a subsequent fix after this one.
