### ISSUE TITLE
`lotus new` should initialize a git repository

### ISSUE THREAD

**Issue by robyurkowski** [lotus/lotus#132]
While I dislike being git-centric, I think this is important behaviour. A plurality of developers are going to be using git, and failing to support that as the default also means that users who quickly add a repository will often miss files that shouldn't be committed, such as `config/.env` et al. which are files that are exceedingly easy to miss.

I realized that I myself contributed my app's session secret earlier as a result. Granted it was the development secret, but if there had been a generated production secret, it would now be in my repository's history.

**Comment by jodosha** [comment]
@robyurkowski Thanks for this suggestion.

I'm for adding a comment in `.env` to explain that it should be put under git history, but to never include production informations in it. The reason is simple: we want a bulk mechanism to add general, non-sensitive informations to the env vars.

**Comment by AlfonsoUceda** [comment]
It's normal to work with git but I think we don't have to suppose that the developer will work with a git repository, maybe it prefers mercurial or another VCS

**Comment by robyurkowski** [comment]
@jodosha I think that's a good idea. We need a comment in .env about putting non-sensitive information in it, and to be honest, we need the same with .env.development and .env.test unless they're going to be `.gitignored`.

 Here's the issue: it's not such a big deal if you commit the development app's secret key, but what if you're testing out Mailgun in development? If you put your API key in `.env.development` as you ought to and then later `git init` a repository, by default, you're going to commit that Mailgun API key and someone's gonna start sending email on your tab. It's worse because it's so easy to do an `ls ./config`, see only `environment.rb`, and then just quickly do a `git add config`.

I think that the only sensibly safe default is to create some sort of repository by default. Using a VCS also conforms to development best practice, and even if some people don't want their code under VCS, the majority will, I suspect.

I am in agreement with @AlfonsoUceda, though. Having done some code spelunking in the past few days, I don't think it would be too challenging to add in a `--vcs=git (default)/hg/.../false` flag to our generator. If you want me to put my money where my mouth is, feel free to assign it to me.

P.S. omg @jodosha change your github handle to @lucaguidi I make that typo every time ;)

**Comment by jodosha** [comment]
### SCM & support

We aren't SCM agnostic. For convenience sake we add some `.gitkeep` files for directories that should be kept around and/or they serve as structure to suggest devs where to put things.

That doesn't mean that we are supporting Git. That is just a trick, we can rename those in `.keep` and stay agnostic. Indeed that `.gitkeep` it's only a convention, and [not officially supported](http://stackoverflow.com/questions/7229885/what-are-the-differences-between-gitignore-and-gitkeep).

Supporting other SCM is out of scope here and not a priority.

@robyurkowski I guess that your suggestion of initialize a Git repo is all about `.gitignore`. If so, what should go there?

### Developer & setup experience

While we all agree about keeping production sensitive informations out of `.env`, we still need to provide a nice experience for devs that clone a repo and want to be able to get productive in a minute or so.

Development/test/staging data is less sensitive. I want to give more weight to productivity here.
If we want to increase security in this area, we can take inspiration from Travis CI's [encryption keys](http://docs.travis-ci.com/user/encryption-keys/). This would be a nice to have, but increases the complexity for us and definitely not a priority.

I don't how having `.sample` files could solve the problems above: security and productivity. It also adds another step: `dev:setup`.

**Comment by jodosha** [comment]
Dear @robyurkowski @AlfonsoUceda and @lotus/core-team 

This is a good idea. After playing with Lotus to eat our own food, I've discovered this a guidance in this is needed. Especially for `.gitignore`.

For instance, I've mistakenly added `db/bookshelf_development/` and `db/bookshelf_test/` directories. Those contain development and testing data for the default database adapter: file system.

My idea is to generate a `.gitignore` with that two directories and to run `git init` automatically when `lotus new` is run.

This should be **skipped** when there is already a repo initialized (check for `.git/` directory). The reason is `lotus new .` (#127). A Git repo may already be present.
