### ISSUE TITLE
Lotus console command history should be enabled by default

### ISSUE THREAD

**Issue by tranvictor** [lotus/lotus#134]
It would be convenient for developers if they are able to navigate through previous commands. IRB disables this feature by default, should Lotus enable it?

**Comment by AlfonsoUceda** [comment]
:+1: I like the history feature, I use it a lot in rails console

**Comment by joneslee85** [comment]
@tranvictor can you cook up a patch?

**Comment by tranvictor** [comment]
I will submit a PR soon.

**Comment by tranvictor** [comment]
Well, after couple of hours, I finally found that IRB doesn't have public API to reset the configuration. The only way we can enable command history feature is changing developers' .irbrc (or some sort) file.
Basically, i had to redefine `IRB.setup` like so to make the feature enabled:
```
module IRB
  def IRB.setup(ap_path)
    # this will initialize :SAVE_HISTORY to nil so setting it
    # before this has no use
    IRB.init_config(ap_path)
    IRB.init_error
    IRB.parse_opts
    # enable command history
    IRB.conf[:SAVE_HISTORY] = 1000
    # ----------------------------
    IRB.run_config
    IRB.load_modules

    unless @CONF[:PROMPT][@CONF[:PROMPT_MODE]]
      IRB.fail(UndefinedPromptMode, @CONF[:PROMPT_MODE])
    end
  end
end
```
I personally think this is not a good solution.

**Comment by huydx** [comment]
@tranvictor i see that you are copy paste the whole stuff from original `IRB.setup`, it's not good. If we are going to monkey-patching, we should use `alias_method`

**Comment by tranvictor** [comment]
@huydx, yeah you are right. Anyway, I dont like monkey-patching much.

**Comment by huydx** [comment]
@jodosha  @joneslee85 i think it's opinionated, but how about using pry as default

**Comment by midas** [comment]
+1 on pry.  No reason to reinvent the wheel here.  And it provides a hist facility that can be greped within the REPL:

hist --grep something

**Comment by jodosha** [comment]
@tranvictor Thanks for opening this discussion, but we don't want to support this feature.

We support different engines out of the box: IRB (default), Pry and Ripl.
I'm keen to keep this simple. Those history tricks requires to increase the complexity of the command, and take care of hidden file artifacts like `.irb-history`.

As @midas suggested, Pry supports this feature natively. If you have this specific need you can add the gem to your `Gemfile` and you're all set! :smiley:
