### ISSUE TITLE
Lotus DB Migration Generator

### ISSUE THREAD

**Issue by joneslee85** [lotus/lotus#136]
**Status:** In Progress
**Taker:** @thecatwasnot 

Hi all

I am in the progress of implementing DB migration at lotus/model and there are much works to be done. I would love to get help from our beloved community in the implementation of the first Lotus Migration generator ever! 

The idea is to implement following CLI: `bundle exec lotus generate migration <name_of_migration>` and it will generate new migration file `/lib/<app_name>/db/migrate/<timestamp>_<name_of_migration>.rb` with content:

```ruby
class <name_of_migration_in_constantized_form> < Lotus::Model::Migration
  def up
  end

  def down
  end
end
```

It is much the same as of Rails migration. There aren't any magic atm.

**Comment by AlfonsoUceda** [comment]
:+1:

**Comment by midas** [comment]
I will take this one if not already taken?

**Comment by thecatwasnot** [comment]
Have started this, got a bunch of boilerplate CLI code done, hopefully can finish and PR tonight.
Do we for sure want this going to `lib/app/db` instead of `db` that exists already?

**Comment by joneslee85** [comment]
@midas @thecatwasnot no one has claimed this ticket yet.

@thecatwasnot your question about the location of db migration is excellent. I have been giving thought about it and I strongly believe that we should place them in `lib/app/db` instead of `db`. Because:

* eventually app in `apps/` could have their own DB setup
* `lib/app` is truly a 1st class of itself

^ @jodosha thoughts?

**Comment by thecatwasnot** [comment]
@joneslee85 I do agree, actually, on second thought.  
Then I'm only waiting on figuring out how to get the app name, I know there was some discussion in #123 on a .lotusrc file that might help.  If we're not going to use the .lotusrc there, I can whip something up quick.

**Comment by joneslee85** [comment]
@thecatwasnot for now, can you please generate it for `db`? 

I will have a look to see how could we retrieve the `app_name` without using `.lotusrc`

**Comment by thecatwasnot** [comment]
@joneslee85 Ok
