### ISSUE TITLE
Lotus DB migration migrate runner

### ISSUE THREAD

**Issue by joneslee85** [lotus/lotus#137]
Assigned to @vinioliveira

Prerequisites: #136 and DB Migration applier in model component

What: Add CLI for run migration for

`bundle exec lotus db migrate`

Please look at my Migrator branch at https://github.com/lotus/model/pull/144 (it is not merged, so please based your work on top of it for now)

**NOTE**: For the time being, we **only** support migrating files in `db/migrations`. Support for migrating files in slice's `apps/<slice>/db/migrations` is to be discussed

**Comment by midas** [comment]
I would suggest staying away from the Rake-ish syntax on this.  Rails overuses (misuses) Rake in my opinion, especially considering the existence of Thor.  Suggested:

bundle exec lotus db migrate

**Comment by thecatwasnot** [comment]
Agreed.

**Comment by joneslee85** [comment]
@midas I deliberately want the syntax to be `db:migrate` instead of `db migrate` because I want to support following syntax in the future:

```
bundle exec lotus db:migrate #migrate lib/app/db/migrate
bundle exec lotus db:migrate web #migrate apps/web/db/migrate
```

**Comment by midas** [comment]
@joneslee85 I am sure you already realize this, but just in case, Thor can support the following syntax using sub commands which will give you the desired API and behavior without the Rake-ish syntax.

```
bundle exec lotus db migrate #migrate lib/app/db/migrate
bundle exec lotus db migrate web #migrate apps/web/db/migrate
```

Just seems a little cleaner to me.  No using the shift key when typing, prettier to look at, etc.

**Comment by joneslee85** [comment]
@midas if so, then I am okay with ^

**Comment by AlfonsoUceda** [comment]
:+1: if thor can, we can ;)

**Comment by vinioliveira** [comment]
@joneslee85  I've started work on this, it's related to db rollback that I also working on.
I'll send a PR shortly.

**Comment by vinioliveira** [comment]
I am wondering if is a good idea create a path option, then, user could define location of migrations.

**Comment by joneslee85** [comment]
@vinioliveira I don't think it is a good idea, for we try to be conventional as much as we could
