### ISSUE TITLE
Lotus DB migration rollback runner

### ISSUE THREAD

**Issue by joneslee85** [lotus/lotus#138]
Assigned to @vinioliveira

Prerequisites: #136 and DB Migration applier in model component

What: Add CLI for run migration:

`bundle exec lotus db rollback`
`bundle exec lotus db rollback --step=2`

Please look at my Migrator branch at lotus/model#144 (it is not merged, so please based your work on top of it for now).

**Comment by AlfonsoUceda** [comment]
@joneslee85 edit the command `bundle exec lotus db rollback`
