### ISSUE TITLE
Lotus add new application for existing application

### ISSUE THREAD

**Issue by AlfonsoUceda** [lotus/lotus#140]
Hi:

It would a good idea create a new command `bundle exec lotus add` this command will create a new application inside `apps` folder, e.g:

`bundle exec lotus add admin`

and then it will create the needed files inside `apps` folder and it will add the needed code in the route of application, in lib or when it's needed.

Thoughts?

**Comment by joneslee85** [comment]
@AlfonsoUceda I'd prefer subcommand `generate slice` or `generate app` than `add`. 

I think that we should explore the app type options `--type`. By default the `--type` fallbacks to `web` type app. Other option is `api` style app which have extra tweaks and configurations for API app. Thoughts?

**Comment by AlfonsoUceda** [comment]
agree, better subcommand like generate slice or app and the type option I like it ;)

**Comment by jodosha** [comment]
@AlfonsoUceda FYI this is already part of the plan ;)

**Comment by AlfonsoUceda** [comment]
@jodosha I opened a post in discourse :P but I wanted discuss about the command

**Comment by joneslee85** [comment]
Closed. Moved to https://discuss.lotusrb.org/t/generator-for-application-or-slice/21/13
