### ISSUE TITLE
Any plans on i18n?

### ISSUE THREAD

**Issue by zavan** [lotus/lotus#141]
I'm creating this issue to start a discussion on i18n, since I didn't find anything.

So, any plans on a internationalization module or integration with a gem?
https://github.com/svenfuchs/i18n seems to be the most popular (https://www.ruby-toolbox.com/categories/i18n).

**Comment by zavan** [comment]
This discussion continues here: http://discuss.lotusrb.org/t/any-plans-on-i18n/18

**Comment by jodosha** [comment]
Moving this discussion to https://discuss.lotusrb.org/t/support-i18n-translation/18/3

**Comment by aar0nr** [comment]
Updated link: https://discuss.hanamirb.org/t/support-i18n-translation/18
