### ISSUE TITLE
Load the app in console

### ISSUE THREAD

**Issue by jc00ke** [lotus/lotus#144]
I was poking around the `console` and wanted to check out the routes. @jodosha had mentioned I could access them by using `MyApp::Routes` but I kept getting a missing constant error.

@joneslee85 informed me in chat that I had to actually load the app, which would mount the `Routes`. He suggested I run `MyApp::Container.new` which did make `Routes` available.

It'd be nice if I didn't have to do that when poking around the `console`. It would also be nice to figure out a way to expose routes for routing specs, but that is a separate issue.

**Comment by jodosha** [comment]
@jc00ke @joneslee85 would you mind to try w/ the referenced PR?

```shell
% lotus new bookshelf --lotus-head=true
```

Then amend the generated `Gemfile` like this:

```ruby
gem 'lotusrb', github: 'lotus/lotus', branch: 'preload-apps-in-console'
```

```shell
% bundle
% bundle exec lotus console
irb(main):001:0> Web::Routes
=> #<Lotus::Routes:0x007fd8b9bdf990 @routes=#<Lotus::Router:0x007fd8ba94bd90 @router=#<HttpRouter:0x3fec5d4a5eb4 number of routes (0) ignore_trailing_slash? (true) redirect_trailing_slash? (false)>
================================================================================================================
Root (0 matchers)>>
```
