### ISSUE TITLE
App generator --template arg

### ISSUE THREAD

**Issue by jodosha** [lotus/lotus#155]
When a new application is generated via `lotus new`, we should allow to pass a new argument: `--template`. This indicates the default template used by the application. If not specified, it defaults to `erb`.

This serves as a base for: [Action generator](https://github.com/lotus/lotus/issues/154) #154.

**Comment by AlfonsoUceda** [comment]
@jodosha and me we was talking about this feature. For now, we can't do this feature, we have detected when we pass the template option, e.g. `--template=haml` we need to replace the default `erb` files with `haml` but we can't support in lotus every template.

We need to create a template generator system for supporting this feature. Like rails does with, e.g. `haml-rails` in the future we'll have similar gems, `lotus-haml`

We have to pospone this feature.

**Comment by jodosha** [comment]
Closing this for now.
