### ISSUE TITLE
Generate adapter config when creating new app

### ISSUE THREAD

**Issue by joneslee85** [lotus/lotus#164]
The idea is to automatically configure Database when creating new app with param `--adapter`. This feature is similar to `rails new -d`. Default option is :filesystem. Other available options are:

* memory
* sqlite3
* postgresql
* mysql2

The generator should generate Gemfile with database adapter gem accordingly, for example `pg` gem for postgresql. Furthermore, the adapter of lib/chirp.rb should be updated with specified adapter.

**Comment by Linuus** [comment]
@joneslee85 Should we also try to insert a correct `DATABASE_URL` in the .env.development and .env.test files?

Like
```ruby
FOO_DATABASE_URL=mysql2://localhost/foo_development
```
in .env.development, when using the mysql2 gem for instance.

**Comment by joneslee85** [comment]
@Linuus yes please

**Comment by Linuus** [comment]
Great!

What about slices? When generating a new application, should the default slice use the same adapter?

Also, when generating a new slice, it should also have the adapter option?

**Comment by joneslee85** [comment]
@Linuus very good question, I vote for leaving slice app as is. And we could provide this same functionality for the app/slice generator feature.

**Comment by jodosha** [comment]
@Linuus I agree with @joneslee85 . Thank you, folks.
