### ISSUE TITLE
Integration with Lotus::Helper

### ISSUE THREAD

**Issue by jodosha** [lotus/lotus#165]
- [x] Make Lotus::Helper a dependency
- [x] Application generator should explicitly include helpers in views (see _Example 1_). This strategy allows devs to toggle this feature.

_Example 1_

```ruby
require 'lotus/helpers' # << NEW

module Web
  class Application < Lotus::Application
    configure do
      # ...
      view.prepare do
        include Lotus::Helpers  # << NEW
      end
    end
  end
end
```

**Comment by tomkadwill** [comment]
Hey @jodosha are you working on this? otherwise I'm happy to take it.

**Comment by jodosha** [comment]
@tomkadwill Please :)

**Comment by jodosha** [comment]
@tomkadwill @joneslee85 I think that `lotus-helpers` should be an hard dependency like `lotus-view` et all.

**Comment by jodosha** [comment]
Closing as it was implemented.
