### ISSUE TITLE
Fix CLI help description for db console

### ISSUE THREAD

**Issue by joneslee85** [lotus/lotus#174]
Taker: Team LEO

It's more issue of Thor than Lotus.

When performing 'bundle exec lotus db console --help'

Expected db console shows in description, however only db returns. The namespace :db is not taking into consideration

**Comment by vinioliveira** [comment]
Here seems to be correct  
![screen shot 2015-03-06 at 8 17 22 pm](https://cloud.githubusercontent.com/assets/341918/6538195/e7964b12-c43d-11e4-9273-43c151b99779.png)

**Comment by joneslee85** [comment]
@vinioliveira that is wrong, it should show `lotus db console`

**Comment by vinioliveira** [comment]
In deed it's thor issue, see erikhuda/thor#464. 

We may append the ancestor command to the description, while they don't fix it.

`
desc 'db console', 'start DB console'
`

**Comment by joneslee85** [comment]
@Linuus ping

**Comment by Linuus** [comment]
@joneslee85 Sorry. I have been very busy lately with moving to a new apartment, celebrating easter and traveled to London for vacation :) I will take a closer look here soon!

**Comment by joneslee85** [comment]
@mymai91 @dondinhit please take on this

**Comment by Linuus** [comment]
Sorry. But if someone else has time, please take it :)

**Comment by DonDinhIT** [comment]
@joneslee85 got you. Team Leo will resolve this issue. thanks Trung
