### ISSUE TITLE
Loading routes for testing

### ISSUE THREAD

**Issue by danelowe** [lotus/lotus#187]
One of my views uses the routes helper, e.g.

```ruby
routes.path(:quotes, id: quote.type)
```

The helper relies on a namespaced Routes module being available, e.g.

```ruby 
Web::Routes
```

This module is never created by ```Lotus::Loader``` unless the application is being loaded as an instance rather than a class. 

To prevent my tests from having errors, I had to change the line in my test_helper.rb from the default

```ruby
Lotus::Application.preload!
```

to 

```ruby
Lotus::Application.preload_applications!
```

I'm not entirely sure what the difference between these is, and whether it will have an impact on testing performance, or if there is an easier way to prevent the routes helper breaking tests?

**Comment by AlfonsoUceda** [comment]
Hi @danelowe there is a PR fixing this behaviour https://github.com/lotus/lotus/pull/180

**Comment by AlfonsoUceda** [comment]
There is a PR fixing that: #180

**Comment by jodosha** [comment]
@danelowe Hello and thanks for reporting this issue. Sorry for the poor experience. :disappointed: 

I've crafted a fix for you. It worked locally.
Would you mind to amend your `Gemfile` with the following code and try again?

```ruby
gem 'lotusrb', github: 'lotus/lotus', branch: 'ensure-to-load-routes-when-testing-in-isolation'
```

Please let me know, and I'll be happy to merge the PR.

**Comment by danelowe** [comment]
@jodosha That works. Thanks! I'd be very interested to see what the PR looks like. 

I'm definitely enjoying Lotus.

**Comment by jodosha** [comment]
@danelowe Here the PR https://github.com/lotus/lotus/issues/188

**Comment by jodosha** [comment]
@danelowe This is in master now, you can change your `Gemfile` accordingly.
I want to wait a few days before to release a patch version. You know, just in case other small issues are found.

Thanks for your patience.

**Comment by danelowe** [comment]
Thanks! :smile:
