### ISSUE TITLE
File named application.* in public dir causes issues

### ISSUE THREAD

**Issue by danelowe** [lotus/lotus#189]
I've reproduced this on a brand new install, e.g.

```
$ lotus new test
$ touch test/apps/web/public/application.css.map
```

Start the dev server, and any page has an error. 

```RuntimeError: No template engine registered for application.css.map```
```
gems/lotusrb-0.2.1/lib/lotus/loader.rb:104:in `module_eval'
gems/tilt-2.0.1/lib/tilt.rb:43:in `new'
gems/lotus-view-0.3.0/lib/lotus/view/template.rb:10:in `initialize'
gems/lotus-view-0.3.0/lib/lotus/view/rendering/templates_finder.rb:73:in `new'
```

The last line in the stack trace leads to 
```ruby
def _load_view_framework!
  namespace.module_eval %{
    #{ namespace }::View.load! 
  }
end
```

I'm having trouble debugging it from there. 

Interestingly if the file is renamed so that it is not called 'application', or the file extension is simply '.css', the error doesn't show.  

Not sure if I'm misunderstanding how static assets should work.

**Comment by joneslee85** [comment]
@danelowe what version of lotus is that? Can you please check your `application.rb` and make sure `templates` is uncommented

```
      # The relative path where to find the templates
      #
      # templates 'templates'
```

**Comment by joneslee85** [comment]
It seems to me you are using the old version of lotus, the new 0.3.0 should have resolved this already

**Comment by danelowe** [comment]
@joneslee85 Had the issue on a project that was installed with 0.2.1 but using master branch for all gems in the Gemfile. Uncommenting the templates config worked. I wish I could understand why.
