### ISSUE TITLE
Load path order

### ISSUE THREAD

**Issue by kirs** [lotus/lotus#190]
Here is my class structure:

```
# controllers/posts/base.rb
module Controllers
  module Posts
    module Base
      # some mixin methods
    end
  end
end

# controllers/posts/home.rb
module Controllers
  module Posts
    module Home
      include Controllers::Posts::Base
      def call(_)
        # some action code
      end
    end
  end
end
```

Depends on the order of files in Lotus `load_path`, sometimes `Base` is loaded before `Home` and the code works fine. But sometimes `home.rb` is loaded first and in this case it `Base` I'm trying to include is not defined yet.

At this moment I had to tweak the `$LOAD_PATH` to require `base.rb` manually from `Home` class.
I was wondering what would the "Lotus way" to fix the problem?

**Comment by joneslee85** [comment]
Hi there

I'd encourage you `require <your_mixin>` in `controllers/posts/home.rb`. If you want this mixin globally available to all controllers, you can put them into the Application class 

```
#...
controller.prepare do
  require <minxin>
  include Module
end
```

**Comment by kirs** [comment]
@jodosha is it OK to modify the `$LOAD_PATH` in Lotus app?

**Comment by jodosha** [comment]
@kirs Lotus doesn't touch `$LOAD_PATH`, so you are free to modify it. However, it seems a dangerous operation that may affect the behavior and/or the performance of `require`. For this kind of situations, I always prefer to use `require_relative`.

If you need that module to be included in **all** your actions, please consider what @joneslee85 have indicated.

**Comment by kirs** [comment]
Thanks!
