### ISSUE TITLE
Destroy command

### ISSUE THREAD

**Issue by sungwoncho** [lotus/lotus#192]
Taker: @sungwoncho 

I would like to suggest a destroy command that can undo generation.

It would read something like:
`bundle exec lotus action destroy web home#index`

Any thoughts?

**Comment by joneslee85** [comment]
@sungwoncho we love it, why don't you give it a go?

**Comment by sungwoncho** [comment]
@joneslee85 Okay, I will try to work on it as my schedule permits.

**Comment by jodosha** [comment]
@sungwoncho This makes sense. I agree with @joneslee85 : would you love to take care of it? Thank you very much.

**Comment by joneslee85** [comment]
@sungwoncho ping ping :)

**Comment by sungwoncho** [comment]
@joneslee85 I won't be able to work on this for two weeks tops. Sorry. If anyone wants to take over while I am not working on this, please feel free. I'll update you when I resume my work on this, if no one takes over in two weeks.

**Comment by joneslee85** [comment]
@sungwoncho thanks for the update.

**Comment by joneslee85** [comment]
@sungwoncho ping :)

**Comment by sungwoncho** [comment]
Working on this this weekend!

**Comment by sungwoncho** [comment]
@joneslee85 I have too much on my plate at the moment. Can't promise any progress any time sooner. Feel free to take over.

**Comment by joneslee85** [comment]
@mymai91 @DonDinhIT can you two take care and wrap up Sung's work? Much thanks

**Comment by mymai91** [comment]
yes, we can.

**Comment by mymai91** [comment]
@joneslee85 I see in the Lotus latest version it has two options generator one for application generator, one for model generator. I guess I'll handle destroy for application and model, right? If not help me make it clearer, please.
Thanks.

**Comment by joneslee85** [comment]
@mymai91 this is to destroy action only

**Comment by mymai91** [comment]
@jodosha: What do you think about grouping under 1 sub-command `action`, let’s me give you examples:
```
lotus action generate
lotus action destroy
```

**Comment by joneslee85** [comment]
@jodosha I'd cast a vote to group under subcommand `action`, I kinda like this pattern.

**Comment by t4deu** [comment]
Hi everyone,

This can be done with a more simple way, since Thor is used by the generators, just need to change the Thor behavior before calling the already existing generators. It even removes settings added to existing files(eg: routes.rb). 

I create a PR with the changes for destroy actions, models and migrations.
