### ISSUE TITLE
Resource generator

### ISSUE THREAD

**Issue by joneslee85** [lotus/lotus#193]
`lotus generate resource <name_of_resource` which does similar things like the counter part of Rails

* create entity
* create repository
* create RESTful route
* create all controller actions
* create all view classes
* create empty templates for all actions
* create tests for actions

**Comment by nguyenngoc2505** [comment]
We take it.

**Comment by sungwoncho** [comment]
Good idea. I'd like to have a go at it for some of the resources you suggested.

**Comment by jodosha** [comment]
@joneslee85 @nguyenngoc2505 Sorry, but this is similar to Rails' scaffolding and I think that is an anti-pattern.
