### ISSUE TITLE
View generator

### ISSUE THREAD

**Issue by sungwoncho** [lotus/lotus#195]
Currently, the action generator also has the responsibility to generate view files. It might be a good idea to extract view generation into a separate generator, and have action generator use view generator while generating an action.

This will also help implementing something like scaffold generator in Rails (See #193). Because scaffold generator can make use of existing generators, passing different options as it sees fit. Any thoughts?

**Comment by jodosha** [comment]
@sungwoncho Hello. What do you mean by extraction? Do you mean to have two different internal objects: one for actions and one for views? Or do you mean to have two different CLI commands like `lotus generate action` and `lotus generate view`?

**Comment by mvader** [comment]
I think that it's a good idea to separate both generators too. Would your proposal include the generation of templates on the view generator?

Imagine the use case of a JSON api that uses no templates. How would it work in that case?

**Comment by sungwoncho** [comment]
@jodosha My suggestion is that we have two different generators `Lotus::Generators::View` and `Lotus::Generators::Action`. Therefore, there will be two different CLI commands. Is this what you mean by having two different internal objects?

@mvader I think it makes sense for view generator to generator templates as well. I think lotus generates a blank .html.`template_suffix` template in every case. I think we can allow people to pass in options to stop generating templates when not needed.

**Comment by jodosha** [comment]
@sungwoncho Gotcha. What's the use case for that? Why would you have two execute two CLI commands instead of one? I see scaffolding as an anti-pattern, we won't have it in Lotus.

@mvader In case of a JSON API, I'd personally not use an action generator, but yeah it makes sense to avoid the generation of view/template. For that use case, we can add `--skip-view` flag to the CLI command. Opening a separated ticket for this.

**Comment by sungwoncho** [comment]
@jodosha My argument for having two generators is that scaffold generator can make use of each generators to generate components independently from one another. But that point is moot if lotus will not have a scaffold generator.

I am curious to learn why you think it's an anti-pattern to have scaffolding.

**Comment by jodosha** [comment]
> I am curious to learn why you think it's an anti-pattern to have scaffolding.

Because you generate a lot production code without a failing test. With BDD/TDD you target one step at the time. Having the action generator is more than enough to make your test to pass.
