### ISSUE TITLE
Content Security Policy Headers

### ISSUE THREAD

**Issue by codyeatworld** [lotus/lotus#204]
When installed fontawesome I noticed that lotus sets a content-security-policy header.

This gave me trouble when the font awesome stylesheets tried to load the fonts in chrome, firefox and safari on my mac. (Yosemite)

![Imgur](http://i.imgur.com/T0lOKMq.png)

I noticed a setting for csp in the application.rb file

```ruby
security.content_security_policy "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self';"
```

I changed it to

```ruby
security.content_security_policy "default-src 'self'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self';"
```

And fontawesome started working, but I still had one error left in the console.

![Imgur](http://i.imgur.com/AZyqyJv.png)

I've never run into this issue before so I booted up new rails app, installed fontawesome and gave it a shot, fontawesome loaded up with zero errors in the console. So then I looked up the headers for the rails app and didn't see anything related to csp. 

Here is a gist of the rails headers that i pulled up: https://gist.github.com/codyeatworld/a45866c2bf8aefc508d3

I'm guessing rails doesn't set any csp headers because they leave it up to nginx or the server.

Also, I havent had time to test it out more, but I also had trouble inlining an image using a src="data:".
Lotus has been lots of fun though! You can find the application im working on here https://github.com/codyeatworld/codyeatworld

@joneslee85

**Comment by joneslee85** [comment]
cc @jodosha

**Comment by AlfonsoUceda** [comment]
@codyeatworld try removing "; style-src: 'self';"

default-src is used by default: https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#style-src

Rails doesn't set this CSP aby default if you see in your gist

**Comment by jodosha** [comment]
@codyeatworld Have you tried with @AlfonsoUceda suggestion? Any news on this?

**Comment by codyeatworld** [comment]
@AlfonsoUceda @jodosha I just tried it and the error in the console says default-src is the problem now.

`
Content Security Policy: The page's settings blocked the loading of a resource at self ("default-src http://localhost:2300").
`

**Comment by AlfonsoUceda** [comment]
@codyeatworld it's weird, can you try only `default-src self;`? thanks ;)

**Comment by codyeatworld** [comment]
same problem with

```ruby
security.content_security_policy "default-src 'self';"
```

console
`
Content Security Policy: The page's settings blocked the loading of a resource at self ("default-src http://localhost:2300").
`

**Comment by AlfonsoUceda** [comment]
@codyeatworld and is that error raised in all browsers?

**Comment by codyeatworld** [comment]
Nope, sorry I forgot to check, it was raised in Firefox 37.0.1 but not Chrome 42.0.2311.90 (64-bit) or Safari 8.0.3.

**Comment by AlfonsoUceda** [comment]
@codyeatworld can you try it in Windows or Linux, maybe can be a Firefox bug, I don't know

**Comment by AlfonsoUceda** [comment]
@codyeatworld ping

**Comment by codyeatworld** [comment]
Thanks for the ping, I should have time to look into again this later tonight. I'm not sure how to try it on windows, but I can try it in ubuntu.

**Comment by codyeatworld** [comment]
I think it might of been a Firefox bug, the error is not present with Firefox Developer Edition, Safari or Chrome after reverting to default CSP settings. 

Only standard Firefox.

Thanks for your time and help!

**Comment by jodosha** [comment]
@codyeatworld Closing this for now, please let us to know if the problem is caused by Lotus instead.

**Comment by AlfonsoUceda** [comment]
@codyeatworld thanks for your help and time ;)
