### ISSUE TITLE
Create Lotus.root

### ISSUE THREAD

**Issue by joneslee85** [lotus/lotus#207]
This will return the root of lotus app

**Comment by AlfonsoUceda** [comment]
@joneslee85 the root of each app inside container?

**Comment by jodosha** [comment]
@joneslee85 @AlfonsoUceda This should return a `Pathname` that is the top level directory of the application. /cc @nguyenngoc2505

**Comment by joneslee85** [comment]
@jodosha can you please add team Leo (@dondinhit and @mymai91) to this ticket instead? cheers

**Comment by jodosha** [comment]
Implemented by #213 :sparkles:
