### ISSUE TITLE
Default Rake task: environment

### ISSUE THREAD

**Issue by jodosha** [lotus/lotus#210]
### Description

Add support for a default Rake task `environment`. This should serve as a base for user defined rake tasks.

Real world example:

```ruby
namespace :storage do
  desc 'Clear local storage'
  task clear: :environment do
    # Here I want to have access to the objects of my application
    # Example:
    BookRepository.clear
  end
end
```

### Implementation hints

```ruby
task :environment do
  require 'lotus/environment'
  require Lotus::Environment.new.env_config
end
```

This article can be helpful for testing this feature: https://robots.thoughtbot.com/test-rake-tasks-like-a-boss

**Comment by joneslee85** [comment]
@nguyenngoc2505 please take on this one

**Comment by joneslee85** [comment]
@nguyenngoc2505 let me know if you need any help with this ticket

**Comment by jodosha** [comment]
@nguyenngoc2505 We're in a hurry today to release v0.3.2, I've assigned it to @AlfonsoUceda cause he's around now. /cc @joneslee85

**Comment by nguyenngoc2505** [comment]
@jodosha Ok, noproblem.

**Comment by joneslee85** [comment]
@nguyenngoc2505 ping

**Comment by joneslee85** [comment]
@AlfonsoUceda are you still on this? If not, I'll take it over from you.

**Comment by AlfonsoUceda** [comment]
please take it ;)
