### ISSUE TITLE
Introduce Lotus.env

### ISSUE THREAD

**Issue by jodosha** [lotus/lotus#211]
This helps to introspect the current environment, by returning a String that allows an introspection.

```ruby
Lotus.env # => "development"

Lotus.env.development? # => true
Lotus.env.production?  # => false
```

**Comment by joneslee85** [comment]
@jodosha I've pair with @nguyenngoc2505 on this issue and we could not come up with any solution that does not monkey-patch and satisfy the requirements at the same time. So I'd like to suggest that we alter the behaviour a bit, what do you think about `Lotus.env` returning an object instead, and users might have to cast `to_s`? maybe? thoughts?

**Comment by joneslee85** [comment]
What do you think about using refinement to monkey-patch the String for `@environment` so we could have introspection for this string obj. Thoughts?

**Comment by AlfonsoUceda** [comment]
@joneslee85 why do you have to monkey-patch?
