### ISSUE TITLE
Allow user to specify lotus version in app generator

### ISSUE THREAD

**Issue by joneslee85** [lotus/lotus#218]
On Rails, you could specify the version of Rails you want to use:

```
rails new _x.x.x_ my_new_app
```

This feature is useful and I want to get it implemented with Lotus too, here are few ideas:

```
lotus new --version=x.x.x my_new_app
```

Thoughts?

**Comment by jodosha** [comment]
@joneslee85 That isn't Rails, but a Rubygems feature. If you try it with lotus, it works as well.

```shell
% gem install lotusrb -v=0.2.0
% lotus _0.2.0_ new bookshelf
% grep lotus bookshelf/Gemfile
gem 'lotusrb',      '0.2.0'
```
