### ISSUE TITLE
Cookies improvements

### ISSUE THREAD

**Issue by jodosha** [lotus/lotus#221]
We should improve Cookies settings.

  - [ ]  Automatic `:secure` option
  - [ ]  Enhance options syntax

## Automatic :secure option

Alongside with `:httponly` we should improve security, by enabling `:secure` option for cookies.
The value for this option should be set by looking at `Configuration#ssl?`.
If we are in production using HTTPS, `#ssl?` will return `true`, and we set `:secure` on `true`.
If we are in development mode, `#ssl?` will be probably `false`, and then `:secure` will be `false` as well.

## Enhance options syntax

Right now we can enable cookies by passing `true` and setting options, by passing a Hash as second argument:

```ruby
cookies true
# or
cookies true, max_age: 300
```

The last syntax seems a little bit odd, we should improve it like this:

```ruby
cookies max_age: 300
```

#### Tech note

**Right now, this proposed syntax enables cookies, but it doesn't set options.**
The reason is that `Config::Cookies#enabled?` coerces the first argument to a boolean, but will then ignore the second one.

**Comment by AlfonsoUceda** [comment]
@jodosha about enhanced options syntax, then will cookies be enabled only if options are passed?
