### ISSUE TITLE
Model generator creates wrong RSpec files.

### ISSUE THREAD

**Issue by jodosha** [lotus/lotus#224]
How to reproduce this:

```shell
lotus new bookshelf --test=rspec && cd bookshelf && bundle
bundle exec lotus generate model user
```

If we look at `spec/bookshelf/entities/user_spec.rb`, it doesn't honor RSpec new way to define specs.

### Expected

```ruby
require 'spec_helper'

RSpec.describe User do
  # place your tests here
end
```

### Actual

```ruby
require 'spec_helper'

describe User do
  # place your tests here
end
```

/cc @joneslee85

**Comment by nguyenngoc2505** [comment]
@jodosha How about `spec/bookshelf/entities/user_repository_spec.rb`? Is it OK with current code?

**Comment by jodosha** [comment]
@nguyenngoc2505 Not sure if I've understood what do you mean. :)

We expect `RSpec.describe` instead `describe` when the current testing framework is RSpec.

**Comment by joneslee85** [comment]
@jodosha really, I only learn about this today.
