### ISSUE TITLE
Puma Heroku Read error: #<NoMethodError: undefined method `each' for #<String:0x007ff1d9e733a8>>

### ISSUE THREAD

**Issue by codyeatworld** [lotus/lotus#234]
When I submit a post request, heroku errors out. This happens locally too.

Live: https://arcane-headland-8567.herokuapp.com/admin/login

Relevant controller: 
https://github.com/codyeatworld/codyeatworld/blob/master/apps/admin/controllers/sessions/create.rb

Relevant form: 
https://github.com/codyeatworld/codyeatworld/blob/master/apps/admin/templates/sessions/new.html.erb

Puma conifg: 
https://github.com/codyeatworld/codyeatworld/blob/master/config/puma.rb

I ran into this article, not sure if this is the same issue: https://proctorit.wordpress.com/2013/05/29/ruby-and-puma-read-error-nomethoderror/

heroku logs:
```
heroku[router]: http_error="Bad chunk" at=error code=H17 desc="Poorly formatted HTTP response" method=POST path="/
admin/sessions" host=arcane-headland-8567.herokuapp.com request_id=ad1b3118-f7cd-47c7-9fdf-06241435cdd5 fwd="73.162.252.23" dyno=web.1 connect=1ms service=181ms status=503 bytes=129
app[web.1]: 2015-05-25 05:22:01 +0000: Read error: #<NoMethodError: undefined method `each' for #<String:0x007ff1d9ebe358>>
app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/server.rb:634:in `handle_request'
app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/server.rb:262:in `block in run'
app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/thread_pool.rb:104:in `call'
app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/server.rb:375:in `process_client'
app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

**Comment by jodosha** [comment]
@codyeatworld Thanks for opening this ticket. Can't really reproduce it locally. It works fine both with good and bad credentials.

From your stack trace, there is an odd detail: the path is `/`, not `/admin/sessions`.
Because I cannot reproduce, can you please remove the line related to Warden and check if it still fails? It could be a matter of integrating Lotus with Warden.

**Comment by codyeatworld** [comment]
@jodosha It was related to Wardens failure app, `response[2]` must be enumerable. I wrapped `response[2]`  in [ ] and it worked!

https://github.com/codyeatworld/codyeatworld/commit/739c97419a3884ea66e5c79df740b18df5a3e308
```ruby
class FailureApp
  def call(env)
    action      = Admin::Controllers::Sessions::New.new
    response    = action.call(env)
    response[2] = [Admin::Views::Sessions::New.render(action.exposures.merge(format: :html, 
                        flash: { alert: env["warden"].message }))]
    response
  end
end
```

Thanks again!
Also, the stack trace path was `/admin/sessions` with a weird line break from the terminal.

**Comment by jodosha** [comment]
@codyeatworld I'm happy that you found the culprit. :+1:
