### ISSUE TITLE
NoMethodError on calling a method defined in application layout from page templates

### ISSUE THREAD

**Issue by mwallasch** [lotus/lotus#235]
Hi,
either i'm doing it wrong or i found an issue regarding view method calls from templates.

Assume there is a method called _notifications_ in the application_layout.rb file

```ruby
module Backend
  module Views
    class ApplicationLayout
      include Backend::Layout
      
      def notifications
        "hello"
      end
    end
  end
end
```
There is no problem to call this method in the _application.html.erb_ file.

But if i try to call this method from another page template, e.g. _templates/home/index.html.erb_ i get an error: NoMethodError: undefined method `notifications'.

**Comment by tomkadwill** [comment]
I've reproduced this and written a failing test. Trying to come up with a fix. 

It seems like the scope does not have access to the layout inside `method_missing`, which is why it is not able to find methods defined on the layout

**Comment by jodosha** [comment]
@tomkadwill That would be really helpful. Thank you! :+1: I think the fix belongs to `lotus-view`, isn't it?

**Comment by jodosha** [comment]
@mwallasch Can you please verify if https://github.com/lotus/view/issues/71 fixes your problem?

@tomkadwill thank you :+1:

**Comment by jodosha** [comment]
Fixed by https://github.com/lotus/view/pull/71
