### ISSUE TITLE
Force SSL

### ISSUE THREAD

**Issue by jodosha** [lotus/lotus#241]
Add a new setting to `Lotus::Configuration` and related generators, to force SSL. See lotus/router#56 for technical details.

```ruby
# apps/web/application.rb
module Web
  class Application < Lotus::Application
    configure do
      # ...
      # force_ssl false
    end

    configure :production do
      force_ssl true
    end
  end
end
```

We should allow to specify this option for Container as well:

```ruby
# config/environment.rb
# …
Lotus::Container.configure(force_ssl: ENV['LOTUS_FORCE_SSL']) do
  mount Web::Application, at: ‘/‘
end
```

For backward compatibility, if that option is not specified, this feature must be turned off.

**Comment by AlfonsoUceda** [comment]
@jodosha when you set in the container then all apps are affected under container, isn't it?

**Comment by jodosha** [comment]
Yes.

We also need to put this setting inside single application's configurations. So they can be enabled on application basis instead of globally.

http://lucaguidi.com
