### ISSUE TITLE
Lotusrc pollutes ENV

### ISSUE THREAD

**Issue by jodosha** [lotus/lotus#243]
When Lotus starts an application, it reads `.lotusrc`. Because the implementation uses `Dotenv.load` to parse it, as side effect, `ENV` is polluted with keys that comes from `.lotusrc`.

```ruby
ENV['architecture'] # => "container"
```

/cc @AlfonsoUceda

**Comment by AlfonsoUceda** [comment]
@jodosha good catch, sorry for the pollution >_<
