### ISSUE TITLE
HTML entities when rendering JSON

### ISSUE THREAD

**Issue by mvader** [lotus/lotus#254]
Hi, I've encountered the following error. I think lotus/view is responsible for this but since I am using it with full lotusrb I posted the error here.

Whenever I render JSON from a view (not the controller or a middleware) my quotes are converted to ```&quot;```. I imagine it will also happen with other characters.
**Example:**
```
{"hello": "world"}
```
Is converted to:
```
{&quot;hello&quot;:&quot;world&quot;}
```

If I render the JSON directly from the controller the response is correct:
```ruby
module Web::Controllers::Home
  class Index
    include Web::Action

    def call(params)
      self.status = 200
      self.body = {
        :hello => 'world'
      }.to_json
    end
  end
end
```

However, this is not:
**controller**
```ruby
module Web::Controllers::Home
  class Index
    include Web::Action

    def call(params)
    end
  end
end
```
**view** (as it should be according to the lotus/view documentation)
```ruby
require 'json'

module Web::Views::Home
  class Index
    include Web::View
    format :json

    def render
      {
        :hello => 'world'
      }.to_json
    end
  end
end
```

**Note:** :json is set as the default format in the app.
My Gemfile.lock: https://gist.github.com/mvader/b2f1ce5634a6e76ff57c

**Comment by jodosha** [comment]
@mvader The reason is that the output of views is auto-escaped for security reasons. If you want to bypass this mechanism, you should use `#raw`.

```ruby
def render
  raw {hello: 'world'}.to_json
end
```

**Comment by mvader** [comment]
Shouldn't it be disabled for JSON format or at least updated on the README? The example could lead to confusion (as it was my case).

**Comment by Haegin** [comment]
+1 on disabling this when the format is JSON or at least updating the docs. At the moment the documentation describes how to set up a view specifically for JSON but doesn't mention that the JSON it generates is completely invalid.

**Comment by raulcoan** [comment]
any updates on this?
