### ISSUE TITLE
Second application routes not found 

### ISSUE THREAD

**Issue by agenteo** [lotus/lotus#262]
I was trying to add a second app to a lotus project.

I've committed my code at https://github.com/agenteo/lab-lotus-two-apps. I can access /play (provided by web app) but could not access /game (provided by game_zone app).

This really shouldn't matter but I already tried to mount the game_zone app on a different segment (/g and /zone) but same not found. 

When I don't mount web I can access game_zone routes.

Here's my lib versions:
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
lotus-controller (0.4.3)
lotus-helpers (0.1.0)
lotus-model (0.3.2)
lotus-router (0.4.0)
lotus-utils (0.4.3)
lotus-validations (0.3.2)
lotus-view (0.4.1)
lotusrb (0.3.2)

**Comment by jodosha** [comment]
@agenteo Hello and thanks for reporting this.

Here's a patch to make your app working:

```diff
diff --git a/apps/game_zone/config/routes.rb b/apps/game_zone/config/routes.rb
index 39ee850..3c075f9 100644
--- a/apps/game_zone/config/routes.rb
+++ b/apps/game_zone/config/routes.rb
@@ -1 +1 @@
-get '/game', to: ->(env) { [200, {}, ['Play!']] }
+get '/play', to: ->(env) { [200, {}, ['Play!']] }
diff --git a/config/environment.rb b/config/environment.rb
index 94a96c2..de0c1ad 100644
--- a/config/environment.rb
+++ b/config/environment.rb
@@ -6,6 +6,6 @@ require_relative '../apps/web/application'
 require_relative '../apps/game_zone/application'
 
 Lotus::Container.configure do
+  mount GameZone::Application, at: '/game'
   mount Web::Application, at: '/'
-  mount GameZone::Application, at: '/'
 end
```

Lotus routing works like this: the first route that satisfies the current request wins. What happens here is that your `/` at the top of the block, acts as a catch-all for all the other applications, so it shadows them.

```ruby
[1] pry(main)> case "/game"
[1] pry(main)* when /\/(.*)/ then puts "web" # This line shadows the rest of the regexps
[1] pry(main)* when /\/game/ then puts "game"
[1] pry(main)* end
web
```

The right thing to do is to put the less greedy path at the bottom:

```ruby
[2] pry(main)> case "/game"
[2] pry(main)* when /\/game/ then puts "game"
[2] pry(main)* when /\/(.*)/ then puts "web"
[2] pry(main)* end
game
```

Which for your application means:

```ruby
# config/environment.rb
# ...
Lotus::Container.configure do
  mount GameZone::Application, at: '/game'
  mount Web::Application, at: '/'
end
```
