### ISSUE TITLE
Render view when status is 400

### ISSUE THREAD

**Issue by mvader** [lotus/lotus#265]
I've noticed that if you set the status to 400 on the controller the view is not rendered. Is that the expected behaviour or is it a bug?

**Comment by jodosha** [comment]
@mvader The current assumption is that only successful responses are rendered by a developer defined view. The rest is managed by the framework that takes care to render special pages.

Is this something that can help? http://lotusrb.org/guides/views/custom-error-pages/

Please let us to know. Thank you! :+1:

**Comment by mvader** [comment]
@jodosha I was using a view to render conditionally the JSON depending on the success or not. But after your reply I thought about it and it was my design that was wrong since I can throw an exception with the errors and the handler will render the error JSON and use the view only for 2XX statuses.

Thanks a lot!
