### ISSUE TITLE
Passing Ruby Object to JS like gon gem

### ISSUE THREAD

**Issue by xuwupeng2000** [lotus/lotus#269]
Do we have something like gon so I can pass Ruby object to Javascript ?
If not then what is the Lotus way of passing these variables ?

I am using HAML and try to do something like
```
:javascript
 $().ready({
    var current_user = #{current_user};
  });
```

But it does not work. Something strips my JS and rendered it as String.
But if I input JS without any Ruby variable this code will work like normal.

**Comment by jodosha** [comment]
@xuwupeng2000 Hello. Can you please share with us an example of the wrong and the expected output? Thank you.

**Comment by safeforge** [comment]
@xuwupeng2000 probably what HAML does is just invoking to_s on the ruby object, so you get something like `#<User:0x007fc24059e5e8>`  if you want to serialize object fields into javascript variable you can try to use `current_user.to_json` like this:

```HAML
:javascript
 $().ready({
    var current_user = #{current_user.to_json.html_safe};
 });
```

**Comment by jodosha** [comment]
@xuwupeng2000 Yes, @safeforge is right. All the template engines perform interpolation via `#to_s`.

I didn't knew about `gon` gem, if it's only for passing a var to JS, it seems overkilling to me. It brings a lot of direct and indirect dependencies.

Here the straightforward, zero dependencies way to solve your problem.

```ruby
# apps/web/views/users/show.rb
require 'json'

module Web::Views::Users
  class Show
    include Web::View

    def json_user
      raw JSON.generate(user.to_h)
    end
  end
end
```

Then in the corresponding template you can use it as `<%= json_user %>`.
That `#raw` method bypass the automatic escape feature that all the views have enabled by default.

http://lotusrb.org/guides/helpers/escape/

@xuwupeng2000 Does it make sense? Am I missing something?

**Comment by xuwupeng2000** [comment]
Thank you!

**Comment by jodosha** [comment]
@xuwupeng2000 Closing this. Thank you.
