### ISSUE TITLE
New Lotus app undefined method jruby?

### ISSUE THREAD

**Issue by tak1n** [lotus/lotus#275]
https://gist.github.com/tak1n/3998872092fe27269a83

Calling it from lotus console works:

```
testapp ➤ be lotus c                                                                                                                                                                                   git:master*
irb(main):001:0> Lotus::Utils.jruby?
=> false
```

**Comment by joneslee85** [comment]
@tak1n I did try to re-produce but it works fine on my box.

**Comment by tak1n** [comment]
If I manually require `lotus/utils` in `code_reloading?` it works too

```ruby
    def code_reloading?
      require 'lotus/utils'
      # JRuby doesn't implement fork that's why shotgun cannot be used.
      if Utils.jruby?
        puts "JRuby doesn't support code reloading."
        false
      else
        @options.fetch(:code_reloading) { !!CODE_RELOADING[environment] }
      end
    end
```

Also if I stop execution with pry here and require `lotus/utils` it's returning `true`, this means it was not required before. Have to dig deeper why it's not already required at this point.

**Comment by tak1n** [comment]
As far as I can see this only `lotus/utils/hash` is loaded the `Lotus::Utils` module defined but the needed class methods like `jruby?` or `rubinius?` are not.

https://github.com/lotus/lotus/blob/master/lib/lotus/environment.rb#L4 here only `lotus/utils/hash` is loaded.

**Comment by tak1n** [comment]
Additional info, from lotus console it works because it doesn't need any `lotus/utils` functionality before it's loaded and at https://github.com/lotus/lotus/blob/master/lib/lotus/commands/console.rb#L27 everything is loaded properly.
