### ISSUE TITLE
ERROR NotImplementedError: fork()

### ISSUE THREAD

**Issue by sebastjan-hribar** [lotus/lotus#278]
Hi,
I'm on Windows 7 with Ruby 2.00 and when running the bookshelf sample application I get:

ERROR NotImplementedError: fork() function is unimplemented on this machine
        C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:27:in `fork'
        C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:27:in `call!'
        C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:18:in `call'
        C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
        C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
        C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
        C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
        C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
        C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
        C:/Ruby200-x64/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
        C:/Ruby200-x64/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
        C:/Ruby200-x64/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'

Can this be fixed or bypassed on Windows 7?

Thank you,
seba

**Comment by jodosha** [comment]
@sebastjan-hribar Hello and thanks for reporting this. Lotus uses a reloadable container (`shotgun` gem) to provide code reload feature to developers. Unfortunately it works with `fork(2)`, which is only available on POSIX systems.

That means you won't be able to use code reloading on Windows. To get your application running, please use `bundle exec lotus server --no-code-reloading`. This should let you use Lotus on windows.

I'm closing this, feel free to reopen, if you're still experiencing problems.

**Comment by SleeplessByte** [comment]
I know this has been long closed, @sebastjan-hribar; I found a way to mimic shotgun as closely as possible:

````Ruby
gem install restart
````

Put in your Gemfile:
````Ruby
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
````

Run in cmd.exe or whatever shell you are using
````Shell
restart bundle exec lotus server --no-code-reloading < nul
````

It is anything but pretty. The restart gem polls for changes in the working directory or subdirectory's, terminates the current process and runs it again. You flood the input channel with `nul` so that the `Terminate batch job (Y/N)?` messages are automagically answered. Finally install the `wdm` gem to use event based file changes instead of polling (which is resource intense).

**Comment by AlfonsoUceda** [comment]
@SleeplessByte thanks for the info ;)

**Comment by SleeplessByte** [comment]
:+1: 

Myself I use a different technique.

Create a `run.bat` file in your root directory:

````bat
start bundle exec lotus server --no-code-reloading < nul
````

Now open a shell in your root directory
````
run
````

It will open a new shell with your server. When you want to re-load the code, just close the prompt and call `run` again.

**Comment by sebastjan-hribar** [comment]
Thank you, I've tried your approach and it worsk fine.

**Comment by gvaldezsan** [comment]
Talking about this again, but shouldn't a small mention to the issue on windows with shotgun be added on the Getting Started Guide?

**Comment by jodosha** [comment]
@gvaldezsan Yes, can you please open a PR for that? Your help would be really appreciated. :+1:

**Comment by gvaldezsan** [comment]
sure, willdo when i get home later!

**Comment by joneslee85** [comment]
@gvaldezsan thanks mate
