### ISSUE TITLE
Support for ZSH (ohmyzsh)

### ISSUE THREAD

**Issue by Eein** [lotus/lotus#282]
I'm running oh-my-zsh as my default shell, and the lotus commands do not work without prepending `noglob`, otherwise giving the following error:

`zsh: no matches found - controller#action`

I fixed this by adding the alias:
`alias lotus="noglob lotus"`

----

I'm not too sure of the internals, but this might be stressful to people trying to get the generators working while using zsh. Figured I'd at least document it here.

Thanks!

**Comment by tak1n** [comment]
Running zsh too, the problem is:

```
bookshelf ➤ lotus generate action web books#read                                                                                                                                                           git:master*
zsh: no matches found: books#read
bookshelf ➤ lotus generate action web books\#read                                                                                                                                                      git:master*
      insert  apps/web/config/routes.rb
      create  spec/web/controllers/books/read_spec.rb
      create  apps/web/controllers/books/read.rb
      create  apps/web/views/books/read.rb
      create  apps/web/templates/books/read.html.erb
      create  spec/web/views/books/read_spec.rb
```

Same goes for rake tasks which has arguments in `[]` you have to escape them -> `\[\]`
This is not a bug in lotus itself.

**Comment by Eein** [comment]
Thanks for the insight :) 

Given that its my own choice to use zsh, I'll go ahead and close the issue. 

Hopefully this will serve as a useful search on google for the people who were as confused as I am.

**Comment by jodosha** [comment]
@Eein I'm [using ZSH here](https://github.com/jodosha/dotfiles) and never experienced this problem. Sorry to hear this.

**Comment by mli-max** [comment]
@Eein @jodosha I had same error only with `bundle exec`
```
bundle exec lotus generate action web home#index --url=/
zsh: no matches found: home#index
```
But that works `lotus generate action web home#index --url=/`
Maybe some bugs with bundler 1.10

**Comment by jodosha** [comment]
@Eein @tak1n @mli-max This must be fixed. :+1: 

Out of curiosity which oh-my-zsh plugins/settings are you using? Would you mind to share. I use it too, and prefix my commands with `bundle exec`, but never ran into this problem. Just want to have a complete understanding of the issue. :smile:

**Comment by Eein** [comment]
I think i use only a couple plugins - 

```
plugins=(git,ruby,rails,golang,colorize) 

export PATH="$HOME/.composer/vendor/bin:/Applications/MAMP/bin/php/php5.6.2/    bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.composer/vendor/bin:/usr    /local/go/bin"

alias clr="clear"

alias lotus="noglob lotus" # my current fix for the weird issue
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
```

That pretty much sums up my .zshrc - everything else is default, including the theme

**Comment by jodosha** [comment]
@Eein Thank you. :smile: Mine is even more complex. :racehorse: 

Here's my version

```shell
zsh --version
zsh 5.0.5 (x86_64-apple-darwin14.0)
```

@mli-max I just tried with Bundler 1.10.5:

```shell
% be lotus generate action web dashboard#index
# ...

% which be
be: aliased to bundle exec
```

**Comment by tak1n** [comment]
@jodosha here my configuration - https://github.com/tak1n/dotfiles/blob/master/.zshrc
