### ISSUE TITLE
Group lotus commands in group

### ISSUE THREAD

**Issue by joneslee85** [lotus/lotus#286]
**What this is about:**

Lotus commands public interface are not consistent. We have commands that belongs to verb action like:

```
lotus new
```

and

```
lotus generate action
lotus generate app
```

and at the same time we have commands grouped by sub-command like:

```
lotus db <do_something>
```

which is not intuitive for user experience.

**What could be made better?**:

I believe that by grouping them in group, we would offer a consistent interface for users that would improve the usability:

```
lotus <group> <command>
```

for example:

```
# generate new action with:
lotus action new <params>

# generate new db migration with:
lotus db new <params>
```

Thoughts?

**Comment by mvader** [comment]
+1. That seems a lot more intuitive.

**Comment by mwallasch** [comment]
Hmm. Why not replacing _generate_ with _new_ at all?

```
lotus new # new project
lotus new app # new sub app
lotus new action # new action in subapp
...

lotus db migrate
lotus db create
...
```

**Comment by theocodes** [comment]
I think i agree with @mwallasch. is there a good argument for having `generate` as well as `new`?

**Comment by mvader** [comment]
```lotus new app``` now creates a new app called ```app```. That command would have to check that the provided parameter is not one of the other actions and that, imho, it would make the code a little bit ugly.

The @joneslee85 approach is more consistent and intuitive. In that approach the commands are always ```lotus <command> <subcommand, if any> args```

With ```lotus new action foo``` it's ```lotus <command> <subcommand> args``` but also ```lotus <command> args``` and here args can replace subcommand depending on what has been provided and it makes the command naming not consistent.

**Comment by theocodes** [comment]
@mvader good point :+1:

**Comment by joneslee85** [comment]
For further discussion, please do it at the forum https://discuss.lotusrb.org/t/group-lotus-commands-in-group/101
