### ISSUE TITLE
New app with --database check type

### ISSUE THREAD

**Issue by mli-max** [lotus/lotus#291]
Why we need duplication for pg and sqlite in https://github.com/lotus/lotus/blob/master/lib/lotus/generators/application/container.rb#L154-L157 
```
 when 'postgresql', 'postgres'
    "postgres://localhost/#{app_name}"
 when 'sqlite', 'sqlite3'
   "sqlite://db/#{Shellwords.escape(app_name)}"
```

Maybe we should use `postgresql`, `pg` and `sqlite3` instead?
and what about specify `file` type too and generate exception if user tries generate with wrong type.

```
       def database_base_uri
          case @database
          when 'mysql'
            "mysql://localhost/#{app_name}"
          when 'mysql2'
            "mysql2://localhost/#{app_name}"
          when 'postgresql', 'postgres'
            "postgres://localhost/#{app_name}"
          when 'sqlite', 'sqlite3'
            "sqlite://db/#{Shellwords.escape(app_name)}"
          when 'memory'
            "memory://localhost/#{app_name}"
          when 'file'
            "file:///db/#{app_name}"
          else
              railse "#{@database} type is not found"
          end
        end
```
because it's so strange when app is generated with wrong db option for example
`lotus new app --database=postgr` I've tried it and have been confused

.gitignore should not has `db` if is not file database but it has
```
/db/favorites_development
/db/favorites_test
```

**Comment by mli-max** [comment]
@jodosha ping

**Comment by joneslee85** [comment]
okay, so it seems the problem lies in the fact that if the type is invalid, the current generator falls back to `file` type.

I agree with @mli-max that UX-wise, it should raise error and exit

**Comment by jodosha** [comment]
@mli-max Thank you for this suggestion. It makes a lot of sense :+1:

**Comment by joneslee85** [comment]
@mli-max do you want to handle this ticket? :)

**Comment by mli-max** [comment]
@joneslee85 Maybe I will do with #297 issue

**Comment by mvader** [comment]
@mli-max did you finally take this? If not I'd be glad to take it.

**Comment by mli-max** [comment]
@mvader ok, you can take it.

**Comment by joneslee85** [comment]
@mvader please have test

**Comment by mvader** [comment]
@joneslee85 of course!

I will start working on it tomorrow

**Comment by jodosha** [comment]
@mvader Hello, thanks for taking care of this. We aim to complete it by the end of today UTC, cause on tomorrow we'll release v0.4.1. Do you think you can handle it on today? Thank you very much! :+1:

**Comment by mvader** [comment]
@jodosha Yes, I think so. If I can’t I’ll let you guys know ASAP so someone has time to take it but I’m pretty sure it’ll be ready by noon

-- 
Miguel Molina
Sent with Airmail

On 9 Jul 2015 at 09:05:27, Luca Guidi (notifications@github.com) wrote:

@mvader Hello, thanks for taking care of this. We aim to complete it by the end of today UTC, cause on tomorrow we'll release v0.4.1. Do you think you can handle it on today? Thank you very much!
