### ISSUE TITLE
Cannot bypass layout in a view

### ISSUE THREAD

**Issue by mwallasch** [lotus/lotus#295]
Hi,

i set ```layout nil``` in a particular view to bypass the layout rendering. But the resulting page contains the layout anyway.

**View:**
```
module Backend::Views::Session
  class New
    include Backend::View

    layout nil
  end
end
```

**Application template:**
```
<!doctype HTML>
<html>
  <head>
    <title>Template</title>
  </head>
  <body>
    <%= yield %>
  </body>
</html>
```

**Page template:**
```
<!doctype HTML>
<html>
  <head>
    <title>Page</title>
  </head>
  <body class="uk-height-1-1">
        <%=
          form_for :signin_form, routes.login_create_path, class: 'pure-form signin-form' do
            email_field :email
            password_field :password

            submit 'Login', class: 'pure-button pure-button-primary'
          end
        %>
      </div>
    </div>
  </body>
</html>
``` 

**Resulting HTML (truncated)**
```
<!doctype HTML>
<html>
  <head>
    <title>TEMPLATE</title>
  </head>
  <body>
    <!doctype HTML>
<html>
  <head>
    <title>PAGE</title>
    
  </head>
  <body class="uk-height-1-1">

        <form action="/backend/login" method="POST" accept-charset="utf-8" id="signin_form-form" class="pure-form signin-form">
...
</form>
   </body>
</html>
  </body>
</html>

**Comment by joneslee85** [comment]
@mwallasch good find, are you able to help with a PR to address this issue?

**Comment by mwallasch** [comment]
@joneslee85 uff. It would be my first. I'll need a little assistance on setup. (especially on debugging in Ruby).

**Comment by AlfonsoUceda** [comment]
@mwallasch could you try with this commit? https://github.com/lotus/view/commit/b170f796d487abeca663d4d2c0751f6b22683b4f

I guess this bug was introduced by this PR https://github.com/lotus/view/pull/73

**Comment by joneslee85** [comment]
@mwallasch sure, I love to. Please give suggestion by @AlfonsoUceda first

**Comment by mwallasch** [comment]
I did. Unfortunately it doesn't solved the problem. Maybe a dependency problem? See Gemfile.lock
https://gist.github.com/mwallasch/54f560719f359b306eae

**Comment by AlfonsoUceda** [comment]
@mwallasch I found the commit https://github.com/lotus/view/commit/c702dfa1a6fbf8e90538b1c6a3251801cbc232cd

I wrote a failing test and fails in this commit, in his parent it passes good
```ruby
require 'test_helper'

describe 'Layout nil' do
  before do
    Lotus::View.unload!

    class ApplicationLayout
      include Lotus::Layout

      def page_title
        'Title:'
      end
    end

    module Articles
      class Index
        include Lotus::View
        layout nil

        def page_title
          "#{ layout.page_title } articles"
        end
      end
    end

    Lotus::View.configure do
      root File.expand_path('../../fixtures/templates/layout/app/templates', __FILE__)
    end
  end

  it 'asdasd' do
    Articles::Index.render(format: :html).wont_include '<!DOCTYPE html>'
    Articles::Index.render(format: :html).wont_include '<html>'
    Articles::Index.render(format: :html).wont_include '<head>WEB</head>'
    Articles::Index.render(format: :html).wont_include '<body>'
    Articles::Index.render(format: :html).must_include '<h1>hello</h1>'
    Articles::Index.render(format: :html).wont_include '</body>'
    Articles::Index.render(format: :html).wont_include '</html>'
  end
end
```

cc @jodosha @joneslee85

**Comment by AlfonsoUceda** [comment]
@mwallasch I remember now, you have to use `layout false` https://github.com/lotus/view/commit/f7f2f9683bf1c11183205fc689e9ddcbdd8d90b3

**Comment by AlfonsoUceda** [comment]
I'm going to create a PR fixing README

**Comment by AlfonsoUceda** [comment]
@mwallasch https://github.com/lotus/view/commits/master fidex

**Comment by mwallasch** [comment]
Aaahh. Okay. I wrote some tests in preparation of a PR but none of them fails. Anyway. false instead of nil solves it.

**Comment by AlfonsoUceda** [comment]
closing
