### ISSUE TITLE
[Error] New project creation

### ISSUE THREAD

**Issue by dm67x** [lotus/lotus#296]
I have Ruby 2.1.6 and I got this error when I would like to create a new project.

E:\websites>lotus new mangascan --database=sqlite
      create  mangascan/.lotusrc
      create  mangascan/.env
      create  mangascan/.env.development
      create  mangascan/.env.test
      create  mangascan/Gemfile
      create  mangascan/config.ru
      create  mangascan/config/environment.rb
      create  mangascan/lib/mangascan.rb
      create  mangascan/lib/config/mapping.rb
      create  mangascan/Rakefile
      create  mangascan/spec/spec_helper.rb
      create  mangascan/spec/features_helper.rb
      create  mangascan/db/schema.sql
      create  mangascan/lib/mangascan/entities/.gitkeep
      create  mangascan/lib/mangascan/repositories/.gitkeep
      create  mangascan/db/migrations/.gitkeep
      create  mangascan/spec/mangascan/entities/.gitkeep
      create  mangascan/spec/mangascan/repositories/.gitkeep
      create  mangascan/spec/support/.gitkeep
      create  mangascan/.gitignore
         run  git init E:/websites/mangascan from "."
C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions.rb:254:in ``': N
o such file or directory - git init E:/websites/mangascan (Errno::ENOENT)
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions.rb:
254:in `run'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/lotusrb-0.4.0/lib/lotus/generato
rs/application/container.rb:95:in `start'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/lotusrb-0.4.0/lib/lotus/commands
/new.rb:30:in `start'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/lotusrb-0.4.0/lib/lotus/cli.rb:7
8:in `new'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:
27:in `run'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.
rb:126:in `invoke_command'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `
dispatch'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440
:in `start'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/lotusrb-0.4.0/bin/lotus:4:in `<t
op (required)>'
        from C:/Ruby21/bin/lotus:23:in `load'
        from C:/Ruby21/bin/lotus:23:in `<main>'

**Comment by joneslee85** [comment]
@dm67x thanks for the bug reporting. We are sorry to let you know that we are not supporting Windows platform. The reason is because there are much more hassles and unexpected errors if developed under Windows and yet deployed to Linux/UNIX platform on production. Please use VirtualBox or install Linux.
