### ISSUE TITLE
CLI Refactoring

### ISSUE THREAD

**Issue by mli-max** [lotus/lotus#297]
I have started to work on cli refactoring based in branch https://github.com/lotus/lotus/tree/cli-refactoring
This issue will be for discussion.

* Extract generator logic from cli and put it in other thor-based object.
* Check types for generate
* Provide more documentation for generate
* Trying to generate something with wrong options user should see understandable message

**Comment by mli-max** [comment]
@jodosha Do you have some thoughts about it?

**Comment by pascalbetz** [comment]
I just ran "lotus generate model" by accident. It created some files, i guess this should raise an error instead:

```
 project$ lotus generate model
      create  lib/project/entities/.rb
      create  lib/project/repositories/_repository.rb
      create  spec/project/entities/_spec.rb
      create  spec/project/repositories/_repository_spec.rb
```

**Comment by mli-max** [comment]
@pascalbetz Yes, model should require name

**Comment by AlfonsoUceda** [comment]
@mli-max like @pascalbetz said. some generators need raise an error or raise a message to tell the user what happended.

**Comment by mli-max** [comment]
@AlfonsoUceda sure

**Comment by pascalbetz** [comment]
One thing that i find handy with Rails is the possibility to revert a
command. Something like:

lotus generate model floo
...adds lots of files
lotus destroy model floo
...removes the files that have been added
lotus generate model foo


AFAIK this is not available currently?

**Comment by AlfonsoUceda** [comment]
@pascalbetz now there isn't a destroy command :(

**Comment by mli-max** [comment]
@jodosha I have a bit confused when I tried to understand a new cli architecture. Can you explain?
For example, I look on model generator
```
require 'lotus/commands/generate/model'
Lotus::Commands::Generate::Model.new(self, environment, name).start
```
I add correct modules and have error `Generate is not a module`. Ok, it's a class. 
What did you plan to add in generate commands? It will do some check for correct input and then call generators with type start action. Is it correct?

**Comment by pascalbetz** [comment]
@AlfonsoUceda 

I haven't looked into the generator structure. But it'd be great if it would provide means do undo a generate much like migrations can be rolled back.

**Comment by mli-max** [comment]
@pascalbetz It would be great. But we will do it in other task. There are refactoring without changing behavior.

**Comment by pascalbetz** [comment]
What is the status of this? Any help wanted?

**Comment by mli-max** [comment]
@pascalbetz I have no time for that.

**Comment by pascalbetz** [comment]
@mli-max have you already started, is there some code to share? i can over this issue.

**Comment by mli-max** [comment]
@pascalbetz I can look into https://github.com/mli-max/lotus/tree/cli-refactoring

**Comment by pascalbetz** [comment]
Thanks. I have started development.

**Comment by pascalbetz** [comment]
FYI: as you can see from the activities on this issue: i'm working on the code... might still take some days to finish and clean up.

Currently i'm working on the app generator+tests.

**Comment by pascalbetz** [comment]
PR Created https://github.com/lotus/lotus/pull/324
