### ISSUE TITLE
Can not create action for app architecture

### ISSUE THREAD

**Issue by pascalbetz** [lotus/lotus#311]
Documentations says that app name must be ommited for app architecture. This does not work and raises an error:

```shell
be lotus generate action foo books#show
Unknown app: `foo'
```

The error is coming from action.rb

```ruby
      def assert_existing_app!
        unless target.join(app_root).exist?
          raise Lotus::Commands::Generate::Error.new("Unknown app: `#{ app_name }'")
        end
      end
```

What seems to work (note the dot as app name): 

```shell
be lotus generate action . foo books#show
```

**Comment by jodosha** [comment]
@pascalbetz The right way to generate an action for app arch is:

```shell
be lotus generate action books#show
```

Just tried it, and works with 0.4.1.

**Comment by pascalbetz** [comment]
hmmm. my bad. sorry.

**Comment by jodosha** [comment]
@pascalbetz No worries :smiley:
