### ISSUE TITLE
Add serve_assets true for production environment by default

### ISSUE THREAD

**Issue by AlfonsoUceda** [lotus/lotus#312]
Talking with @mwallasch in lotus chat, he told us he had problems with heroku serving assets, the solution was add `server_assets true` to production environment.

It makes sense add by default in this environment server assets.

**Comment by pascalbetz** [comment]
Hello @AlfonsoUceda 

I'm working on the generator refactoring (#297) and could add this as well. I assume #297 will raise some discussions as there is a lot of change. So if this is urgent, then better do it separately. Le me know what you think.

**Comment by AlfonsoUceda** [comment]
@pascalbetz don't worry, it isn't urgent ;)

**Comment by tak1n** [comment]
IMO serving static assets in production should be done through a server like nginx or apache, therefore the current default (disabled) in production is good.

**Comment by joneslee85** [comment]
@AlfonsoUceda IMHO it should be done with nginx, users can choose to serve it by manually set it to true but I don't think it is a good default behaviour

**Comment by AlfonsoUceda** [comment]
You are right folks, this task should be done by apache, nginx or other. It seems in heroku should be set to true but the good default configuration should be disabled.

Closing the issue.

cc @mwallasch
