### ISSUE TITLE
Authentication solution

### ISSUE THREAD

**Issue by benlovell** [lotus/lotus#316]
After speaking with @joneslee85 on twitter - this is to start a discussion on what's needed for an (initial cut) authentication solution for lotus.

Are we looking at something real simple such as `has_secure_{password,token}` or something more fully featured such as devise?

Let's try and get a checklist in here that I can use as a plan.

https://github.com/lotus/model/pull/230

**Comment by pascalbetz** [comment]
Just something simple, like has_secure_password. To start with at least. 
If something special needed then more a set of tools that one can use to program rather than something that is configurable like devise.

**Comment by joneslee85** [comment]
IMHO a simple solution like `has_secure_password` does the job for now, please do it in a mixin module

**Comment by SleeplessByte** [comment]
Until then one can always include `ActiveModel::SecurePassword`.

Don't forget the `has_secure_token` implementation!

**Comment by joneslee85** [comment]
Closed because https://github.com/lotus/model/pull/230 is closed

@benlovell can you please extract it to a gem?
