### ISSUE TITLE
Instantiating Lotus::Environment creates the .lotusrc file

### ISSUE THREAD

**Issue by pascalbetz** [lotus/lotus#318]
Since the lotusrc file gets written with default values (if it does not exist) when Lotus::Lotusrc is instantiated, every class that uses L::Lotusrc might write a file as a sideeffect.

I don't think that this is nice behavior of a class (even though it is documented in L::Lotusrc, it is unclear what class is instantiating it).

I'd propose to remove this "auto-write".

The .lotusrc file should be added by a generator (lotus new) or manually., i think. If the file is not there and L::Lotusrc is used, then the default values should be returned.

What do you think?

**Comment by joneslee85** [comment]
Please move it to discuss.lotusrb.org
