### ISSUE TITLE
Error management

### ISSUE THREAD

**Issue by josemota** [lotus/lotus#320]
I didn't really know where to scope this issue due to its potential across multiple components of the framework. So here's my take on the subject.

I thought to myself that developers should be better assisted regarding expected errors. For instance, I didn't have the appropriate template for an action in my Lotus project and so I would get a rather cryptic message like: `undefined method 'render' for nil:NilClass`. After some time digging through I found the cause and I immediately thought that the error message was rather misleading. A much better experience would be to have a descriptive exception being raised, with something like: `The template '<my_template>' is missing.` The text can certainly be improved.

I mention this particular scenario is `lotus/views` but this should apply to everything related to the developing with the framework's components. I would love to get your feedback on this as I thing it will greatly improve the overall experience of using Lotus.

**Comment by jodosha** [comment]
@josemota Absolutely. This "friendly errors" principle is already in the Lotus code base, but not everywhere. This is a must for most common errors like this.

I believe these poor communicative cases are hard to spot in code, but we can fix one by one, once we ran into them.

For instance, do you want to help with that specific error that you have found?

Thank you.

**Comment by josemota** [comment]
Absolutely. I'm in the middle of some hardcore recording spree for my job but once that's done, I'll pick it up. I'll mention this on chat when I do so we can talk about it.

**Comment by jodosha** [comment]
@josemota I'm closing this as it's too vague as a scope. This is a value that we need to consider while writing code, rather than a specific issue to solve.

I encourage you to open PRs to fix each single misleading error message that you'll find while developing apps with Lotus. :hand: :hamster:

**Comment by josemota** [comment]
Sure thing, Luca. Thanks for doing this, I'll make sure to submit PRs along the way.
