### ISSUE TITLE
Middlewares get executed in reverse order?

### ISSUE THREAD

**Issue by trexnix** [lotus/lotus#326]
*This might be a silly question. I'm a newbie to the Ruby and OSS world.*

According to [this guide](http://lotusrb.org/guides/actions/rack-integration/), we're able to add other components to the middleware stack. I decided to do a test and found out that user-defined middlewares got executed in reverse order as they were declared. For example, I have two middlewares as following:

```ruby
class FirstMiddleware
  def initialize(app)
    @app = app
  end

  def call(env)
    env['something'] = 'Hahaha' // Will try to get this value in the SecondMiddleware
    @app.call(env)
  end
end

class SecondMiddleware
  def initialize(app)
    @app = app
  end

  def call(env)
    p env['something'] // This would be nil
    @app.call(env)
  end
end
```

then register them to the stack in `application.rb`:

```ruby
middleware.use FirstMiddleware
middleware.use SecondMiddleware
```

The `env['something']` in `SecondMiddleware` got a value of nil. If I declared the `SecondMiddleware` before the `FirstMiddleware`, it would work as expected. This behavior doesn't seem right to me. I tried to test this with Sinatra and Rails as well and they worked as I expected. Is it intentional? Am I missing something?

**Comment by jodosha** [comment]
@trexnix Hello and welcome :)

We prepend middleware: here's the [commit](https://github.com/lotus/lotus/commit/cb5f87d8dc0ea51188da8b47f6fdcf2ec17344f3) and here's the [reason](https://github.com/lotus/lotus/issues/283).
