### ISSUE TITLE
Generating app with submodule

### ISSUE THREAD

**Issue by MarcelEeken** [lotus/lotus#330]
I was trying to generate an app with a subdirectory, for example api/v1. This almost worked as expected but I found two small problems.

When running `lotus generate app api/v1` and there is no api app available it generates the following application for that app

    module Api::V1
    end

And that gets included in the `config/environment`, but the loading of that file fails because the Api module doesn't exist yet. This was fixed by changing the module to the following format:

    module Api
      module V1
      end
    end

And the second problem I found when running `lotus generate app ap1/v1` is that it tries to generate a spec folder for that app. But that folder is apparently placed relative to the folder where the app is created. It creates the `:project_name/apps/api/v1` folder and places the spec in `:project_name/apps/spec/api/v1` instead of `:project_name/spec/api/v1`.

**Comment by jodosha** [comment]
@MarcelEeken Hello and welcome :)

This is a limitation, the application **must** be at the second level in Ruby namespacing.

```ruby
# valid
Bookshelf::Application
APIV1::Application
Admin::App
Metrics::Application

# invalid
AP1::V1::Application
```
