### ISSUE TITLE
Can't generate an app in Rubinius

### ISSUE THREAD

**Issue by ashmoran** [lotus/lotus#332]
I'm new to Lotus, I thought I'd give it a go today. I have Rubinius 2.5.8 set as my default Ruby, but when I run `lotus new lotus_test`, it fails with this error:

    % lotus new lotus_test        
          create  lotus_test/.lotusrc
          create  lotus_test/.env
          create  lotus_test/.env.development
          create  lotus_test/.env.test
          create  lotus_test/Gemfile
          create  lotus_test/config.ru
          create  lotus_test/config/environment.rb
          create  lotus_test/lib/lotus_test.rb
          create  lotus_test/lib/config/mapping.rb
          create  lotus_test/Rakefile
          create  lotus_test/spec/spec_helper.rb
          create  lotus_test/spec/features_helper.rb
          create  lotus_test/lib/lotus_test/entities/.gitkeep
          create  lotus_test/lib/lotus_test/repositories/.gitkeep
          create  lotus_test/db/.gitkeep
          create  lotus_test/spec/lotus_test/entities/.gitkeep
          create  lotus_test/spec/lotus_test/repositories/.gitkeep
          create  lotus_test/spec/support/.gitkeep
          create  lotus_test/.gitignore
    An exception occurred running /Users/ashmoran/.gem/rbx/2.1.0/bin/lotus

    undefined method `empty?' on an instance of Pathname. (NoMethodError)

    Backtrace:

             Kernel(Pathname)#empty? (method_missing) at kernel/delta/kernel.rb:78
                     Shellwords.escape (shellescape) at /Users/ashmoran/.rubies/rbx-2.5.8/gems/gems
                                                        /rubysl-shellwords-2.0.0/lib/rubysl/shellwords
                                                        /shellwords.rb:74
     Lotus::Generators::Application::Container#start at /Users/ashmoran/.gem/rbx/2.1.0/gems/lotusrb-0.4.1/lib
                                                        /lotus/generators/application/container.rb:94
                          Lotus::Commands::New#start at /Users/ashmoran/.gem/rbx/2.1.0/gems/lotusrb-0.4.1/lib
                                                        /lotus/commands/new.rb:30
                                      Lotus::Cli#new at /Users/ashmoran/.gem/rbx/2.1.0/gems/lotusrb-0.4.1/lib
                                                        /lotus/cli.rb:78
                                   Thor::Command#run at /Users/ashmoran/.gem/rbx/2.1.0/gems/thor-0.19.1/lib/thor
                                                        /command.rb:27
         Thor::Invocation(Lotus::Cli)#invoke_command at /Users/ashmoran/.gem/rbx/2.1.0/gems/thor-0.19.1/lib/thor
                                                        /invocation.rb:126
                                       Thor.dispatch at /Users/ashmoran/.gem/rbx/2.1.0/gems/thor-0.19.1/lib
                                                        /thor.rb:359
               Thor::Base::ClassMethods(Class)#start at /Users/ashmoran/.gem/rbx/2.1.0/gems/thor-0.19.1/lib/thor
                                                        /base.rb:440
                                   Object#__script__ at /Users/ashmoran/.gem/rbx/2.1.0/gems/lotusrb-0.4.1/bin
                                                        /lotus:4
                                  Kernel(Object)#load at kernel/common/kernel.rb:498
                                    Object#__script__ at /Users/ashmoran/.gem/rbx/2.1.0/bin/lotus:23
                     Rubinius::CodeLoader#load_script at kernel/delta/code_loader.rb:66
                     Rubinius::CodeLoader.load_script at kernel/delta/code_loader.rb:152
                              Rubinius::Loader#script at kernel/loader.rb:656
                                Rubinius::Loader#main at kernel/loader.rb:842

Maybe it's a Rubinius issue but I thought I'd report it here, as more likely someone would know what is causing it. AFAIK `Pathname` doesn't implement `#empty?` so I don't know where it's supposed to come from. Is it anything I can fix easily?

I don't have any trouble with MRI 2.2.3 so I'll use that instead.

**Comment by AlfonsoUceda** [comment]
@ashmoran for now lotus it isn't supported by rubinius see [1], now we are focusing hit version 1.0 as fast as we can

[1] https://github.com/lotus/lotus/blob/master/.travis.yml#L25

**Comment by ashmoran** [comment]
@AlfonsoUceda Thanks for the information, I understand your priorities.

**Comment by joneslee85** [comment]
@ashmoran we welcome contribution to better support rbx. Are you up for a PR? ;)

**Comment by ashmoran** [comment]
@joneslee85 Hehe, I certainly don't mind taking a look at this. However it won't be for at least another month, as I am doing too many other things right now. If nobody has looked at by the time I finish the first release of the app I'm working on I'll try to fix this one myself.

**Comment by jodosha** [comment]
@ashmoran Thanks for reporting this, but we don't support Rubinius right now. As @joneslee85 said, we're happy to accept pull requests for this kind of improvement.
