### ISSUE TITLE
Asset directories overwrite earlier directories

### ISSUE THREAD

**Issue by SleeplessByte** [lotus/lotus#333]
Given this structure:
- apps
  - web
    - assets
      - fonts
      - images
      - javascripts
        - application.js
      - stylesheets
        - application.css
    - ...
    - vendor
      - fonts
      - images
      - javascripts
        - jquery.js
      - stylesheets
        - basecss.css
     - ...
- ...

Given the configuration:
````Ruby
module Web
  class Appliction > Lotus::Aplication
    configure do
      # ...
      
      assets << [
        'assets',
        'vendor',
      ]
      
      #...
      serve_assets true #for the current env.
      #...
  end
end
````

Expected the following to be served under the mounted path
- `javascripts/application.js`,
- `javascripts/jquery.js`, 
- `stylesheets/application.css` and 
- `stylesheets/basecss.css`

Actually these are served under the mounted path:
- `stylesheets/basecss.css`
- `javascripts/jquery.js`, 

**Workaround**:
- Give all the sub-directories unique names or flatten the vendor folder.

Why is this not a good workaround?
- Paths should be merged, not overwritten. 
- Earlier entries (assets) should survive later entries (vendors) so you can overwrite files.
- Vendor files may depend on fixed paths which makes the workaround cumbersome

**Comment by joneslee85** [comment]
cc @lotus/core-team

**Comment by jodosha** [comment]
@SleeplessByte @joneslee85 I've crafted a PR to fix this. Would you mind to review #342

**Comment by SleeplessByte** [comment]
Will do!
