### ISSUE TITLE
Default font-src: self in generated application.rb

### ISSUE THREAD

**Issue by SleeplessByte** [lotus/lotus#334]
Where https://github.com/lotus/lotus/issues/204 changed the `default-src` to self, for completeness the default value should be

````Ruby
security.content_security_policy "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self'; font-src 'self';"
````

Keeping `default-src 'none'` and adding `font-src 'self';`

**Comment by joneslee85** [comment]
@SleeplessByte can you please create a PR? TIA

**Comment by SleeplessByte** [comment]
:+1:
