### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by davejlong** [lotus/lotus#335]
I have a Lotus application that I accidentally left running in Tmux on my laptop overnight (about 24 hours total). When I noticed my laptop slowing down today, I checked memory usage to find out that on my 8gb MacBook Pro, Ruby was using 24gb of RAM. The application is still very small: 2 containers; 1 with no actions and 1 with 2 actions and no extra external libraries or anything extra in the libs. The application was just created this week, so it's the latest version of Lotus that I know of.

![Screenshot](https://www.evernote.com/shard/s21/sh/b25bc89e-3900-4d61-8a5a-31b1712d7153/5d5e08471fe1e57a/res/4dd69bd4-21cd-4a4e-ac8d-c0157100cfd7/skitch.png)

Since it's still early enough in the project, I through all the code on [GitHub](https://github.com/davejlong/coh) so that you can see if I've done anything to cause the memory leak.

**Comment by davejlong** [comment]
![Screenshot](https://www.evernote.com/l/ABWyW8ieOQBNYYpaMbFxLXFTXV4IRx_h5Xo)

**Comment by davejlong** [comment]
Since it's still early enough in the project, I through all the code on [GitHub](https://github.com/lotus/lotus/issues/335) so that you can see if I've done anything to cause the memory leak.

**Comment by joneslee85** [comment]
@davejlong thanks for the bug report, can you please provide more details for our investigation? Details like the Ruby version, DB adapter, etc.

**Comment by davejlong** [comment]
$ ruby -v
    ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
    $ bin/lotus version
    v0.4.1
    $ env | grep _system
    _system_type=Darwin
    _system_name=OSX
    _system_version=10.10
    _system_arch=x86_64
    $ rvm --version
    rvm 1.26.11 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]

Database Adapter: Postgres (pg)

Let me know if there's anything else you'd like.

**Comment by jodosha** [comment]
@davejlong Thanks for reporting this. How long the process was alive? Was code reloading disabled (see `lotus server --help`)? If code reloading was enabled (default), did you triggered a lot of reloads via browser refresh?

**Comment by davejlong** [comment]
The process was alive for ~24 hours and code reloading was enabled. Looking at `$STDOUT`, there was only ~10 requests on the app.

I haven't been able to replicate the error since then. I have a feeling that it was related to leaving the app running while closing and reopening my laptop a few times, moving between different networks and different interfaces and other general actions that normally the app wouldn't run during.

**Comment by jodosha** [comment]
@davejlong Thanks for getting back on this. Is COH the application you're talking about? I'll try to do the same thing on my computer.

**Comment by davejlong** [comment]
Yes, COH is the application.

**Comment by jodosha** [comment]
I've left open an application of mine inside a Tmux session for 37 hours now.

```shell
[2015-10-15 10:06:57] INFO  WEBrick 1.3.1
[2015-10-15 10:06:57] INFO  ruby 2.2.3 (2015-08-18) [x86_64-darwin14]
[2015-10-15 10:06:57] INFO  WEBrick::HTTPServer#start: pid=40305 port=2300
```

Here's the memory usage: `20,5Mb`

<img width="801" alt="screen shot 2015-10-16 at 18 46 49" src="https://cloud.githubusercontent.com/assets/5089/10547693/54fb8692-7436-11e5-8e57-b8bf570af35d.png">

I'm closing this for now, but we'll keep an eye, if this will happen in the future to somebody else.

**Comment by davejlong** [comment]
:+1:

I agree. I have not been able to reproduce the issue on my system.
