### ISSUE TITLE
Logging utilities

### ISSUE THREAD

**Issue by jodosha** [lotus/lotus#34]
Add logging utilities for each Lotus application. An idea on how to implement is to generate a `Bookshelf::Logger` class for a `Bookshelf::Application`.

**Comment by joneslee85** [comment]
@vuvanly are you still working on this feature? I haven't heard back from you and @huydx has expressed his interest in giving this a go. So please let me know asap.

**Comment by jodosha** [comment]
As part of this plan, I would love to see a replacement of `Rack::CommonLogger` to be used in [`Lotus::Server#middleware`](https://github.com/lotus/lotus/blob/master/lib/lotus/commands/server.rb#L36).

Please remember that if we want to tag the request with an unique ID, we have [`Action#request_id`](https://github.com/lotus/controller/blob/master/lib/lotus/action/rack.rb#L141) for the purpose.

**Comment by vuvanly** [comment]
Sorry for late response. Recently i have somethings to do, so in the near
future i think i cannot follow it. Sorry for this inconvenience.

On Sat, Jan 3, 2015 at 4:33 PM, Trung Lê <notifications@github.com> wrote:

> @vuvanly <https://github.com/vuvanly> are you still working on this
> feature? I haven't heard back from you and @huydx
> <https://github.com/huydx> has expressed his interest in giving this a
> go. So please let me know asap.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lotus/lotus/issues/34#issuecomment-68586454>.
>



-- 
*Vũ Văn Lý *
*Ruby on Rails Developer*

*Address: 15/32/48A, Vo Duy Ninh, Binh Thanh
<https://www.google.com/maps/place/13+V%C3%B5+Duy+Ninh,+22,+B%C3%ACnh+Th%E1%BA%A1nh/@10.791769,106.7145395,17z/data=!3m1!4b1!4m2!3m1!1s0x317528adb2a0fdeb:0xc799215398cdaed4>*
Hometown*: *Hoang Mai, Nghe An
<https://www.google.com/maps/place/QL+1A,+%C4%90%E1%BB%93ng+M%E1%BB%97i,+Qu%E1%BB%B3nh+Xu%C3%A2n,+Qu%E1%BB%B3nh+L%C6%B0u/@19.2258856,105.6946963,17z/data=!3m1!4b1!4m2!3m1!1s0x31377484a4a31ae3:0x9ec4d64f0f0f52b8>
Email: vanly.se05@gmail.com
*Phone: (+84) 1657 656 050 *
Skype: *vanly.se05*
