### ISSUE TITLE
Stop users from generating model with names that is not a valid ruby classname

### ISSUE THREAD

**Issue by joneslee85** [lotus/lotus#348]
```
bundle exec lotus generate 1235
```

As you can the naming is not a valid ruby classname and thus would yield error when you run the app.

We want to block users from having naming that is not a valid inflected classname

**Comment by jasoncharnes** [comment]
This would be something I'd be willing to take a stab at.

**Comment by joneslee85** [comment]
@jasoncharnes please give it a go

**Comment by jasoncharnes** [comment]
@joneslee85 will do! should be able to work on it this weekend. thanks!

**Comment by jasoncharnes** [comment]
@joneslee85 could you explain, or provide an example, of a non-valid inflected class name? Sorry, just want to make sure I'm covering all the bases.

**Comment by joneslee85** [comment]
We inflect snake case name to valid Ruby class name. A valid class name can contain number but could not start with a number. Solution for this problem can be:

* regex to detect format then throw error
* regex to detect format then append a non-number prefix, eg `Migration123CreateMyTable`

**Comment by joneslee85** [comment]
I like th first approach
