### ISSUE TITLE
Noob Question about testing

### ISSUE THREAD

**Issue by DanielBlanco** [lotus/lotus#350]
Hi Guys, I love what you are doing with Lotus it is a great framework.

I'm following the [Getting Started](http://lotusrb.org/guides/getting-started/) guide and I have troubles understanding the specs, specifically where  should I put my tests.

The current structure is like this:
```
└── spec
     ...
    └── web
        ├── controllers
        ├── features
        └── views
```

From what I understand so far:
* __spec controllers__ are to test exposure data to the view, the response code, headers, etc.
* __spec views__ are to test the rendered string and some helper methods?
* __spec features__ are to test the rendered html?

My question is: if I need to test for example that an user's First Name is being rendered in the page, where should I put my test? in a view spec or in a feature spec?

I would love some guidelines.

Thank you and keep the good work!

**Comment by joneslee85** [comment]
`featrures` test is the end-to-end test where you test the behaviour from user perspective with the browser.

In your case, you should test it with `view` test

**Comment by DanielBlanco** [comment]
Based on your answer I need to test the content in the `views` tests and behaviour like user clicks and routes in features tests.

Thank you!
