### ISSUE TITLE
Namespaced domain classes

### ISSUE THREAD

**Issue by fuadsaud** [lotus/lotus#364]
While building my first Lotus application I've noticed one thing that IMO doesn't seem to follow the best practices for developing ruby applications: generated entities/repositories get created under `lib/application_name/{entities,repositories}`, but unlike common practice in Ruby libraries, these classes are created in the global namespace instead of under `ApplicationName::Entities::EntityName` or `ApplicationName::Repositories::RepositoryName`.

Is there any strong argument in favor of using the global namespace in these cases? This namespacing strategy seems to me the most obvious and best conforming to common Ruby practices.

**Comment by noahc** [comment]
This is just a shot in the dark as I just discovered the project yesterday, but don't you want to be able to use your entities and repositories across all interfaces (or apps)?

**Comment by joneslee85** [comment]
@fuadsaud the main purpose for not namespacing our entities/repositories is the share-ability. Codes, especially domain logic codes conventionally should not belongs to any apps and be placed under `/lib`. You can have your own namespaced code if you prefer, please put them under `apps/<name>`

**Comment by mjacobus** [comment]
I'm with @fuadsaud on this one. 

If the application business is really decoupled from the framework, and if I got it right, this is one of the goals of lotus, that can have its own namespace. It can even be shipped aas gem and "easily" be transferred to other frameworks.

I am currently working on an app where I am manually creating namespaces for repos/entities and so on. I plan on finishing a feature today and do a little refactoring. Once I have that ready I will link some code here to exemplify what I mean.

**Comment by mjacobus** [comment]
Ok, I think I could achieve what I was planning to achieve today, although my example app is far from finished. I referenced some files in [this question](https://github.com/lotus/model/issues/240).

- [lib/application](https://github.com/mjacobus/quizzy/tree/0ea7ecb82b0fec26000f9e319b2ac13fb74b1601/lib/application)
  * application services
  * application factories
- [lib/quizzy](https://github.com/mjacobus/quizzy/tree/0ea7ecb82b0fec26000f9e319b2ac13fb74b1601/lib/quizzy) - the application business logic.

**Comment by jodosha** [comment]
> It can even be shipped aas gem and "easily" be transferred to other frameworks.

@mjacobus What do you mean with the last part of the sentence?

**Comment by jodosha** [comment]
@fuadsaud @mjacobus Yes, the application that lives under `lib/` can be packed as a gem and distributed to other applications in your product infrastructure. For instance, if you deploy JSON API to a different server, you may want to extract a private gem and make many apps to share the same domain logic.

Now the reason of not namespacing them is to avoid verbosity. Polluting global namespace shouldn't be a problem for application while it is for public gems. For instance, if I release a `foo-authentication` gem on Rubygems, that "squats" `User` and prevents devs to use that constant name in their applications. Namespacing makes sense there.

**Comment by mjacobus** [comment]
@jodosha I mean that when it has their own namespaces, the domain classes are not likely to collide with any other class even when moved to different applications. Then they can be extracted into gems.
