### ISSUE TITLE
lotus new . creates unwanted subdirectory in some cases

### ISSUE THREAD

**Issue by mwallasch** [lotus/lotus#366]
Version: HEAD

If i run the `lotus new .` command to create a new project inside an existing directory, it creates the project in a new subdirectory with the same name as the root dir instead of using the root dir itself. 

Steps to reproduce:
1. create a folder e.g. lotus_test and cd into that directory
2. create a Gemfile as shown below
3. run bundle install
4. run bundle exec lotus new .

Subdirectory is created.

As @AlfonsoUceda suggested the error may lay here:
https://github.com/lotus/lotus/commit/d9ca958bfeeec98893d478b802ce80a141f168ea#diff-3394769438b4229c5c6d442abe4e5cbaR29

Content of Gemfile:
```
source "https://rubygems.org"
ruby "2.2.3"

gem "bundler"
gem "rake"
gem "thin"

gem "lotusrb", github: "lotus/lotus"
gem "lotus-controller", github: "lotus/controller"
gem "lotus-view", github: "lotus/view"
gem "lotus-helpers", github: "lotus/helpers"
gem "lotus-validations", github: "lotus/validations"
gem "lotus-router", github: "lotus/router"
gem "lotus-utils", github: "lotus/utils"
```

**Comment by AlfonsoUceda** [comment]
Thanks @mwallasch for the PR. If you want you can fix the bug, it was introduced with the cli refactoring.
