### ISSUE TITLE
[Proposal] Initializers

### ISSUE THREAD

**Issue by lucasallan** [lotus/lotus#367]
Hi guys,

I'm wondering if you guys are considering adding something like `Rails Initializers`. 
This is something that I could work on.

**Comment by jodosha** [comment]
@lucasallan Hello :smile: Do you mean something similar to: `config/initializers/*.rb`? Or before/after callbacks to fire when the app is going to be loaded and when it's done?

**Comment by lucasallan** [comment]
@jodosha I'm thinking about something similar to `config/initializers/*.rb`.

**Comment by theocodes** [comment]
i :+1:  this. In my understanding, simply having a place/dir where all files get loaded automatically would add a consistent place to put config blocks etc. In the projects I'm working on, we end up having initializers in different places which I believe to be confusing :/

**Comment by jodosha** [comment]
@lucasallan @theocodes Before to add any feature to Lotus, I always wonder if it can be easily solved via Ruby. In this case, what if you do?

```ruby
# config/environment.rb
# ...
Dir["config/initializers/**/*.rb"].each {|file| require file }
```

**Comment by theocodes** [comment]
Yes sure. But like i said, this would be for consistence more than anything else..  It would also help with future development of gems that are designed to work with lotus.  :)

**Comment by lucasallan** [comment]
@jodosha I agree with @theocodes

**Comment by jodosha** [comment]
It's Friday evening and I'm tired, that's why I'm saying yes to this feature :wink:

@lucasallan Can you please implement it? It should:

  1. happen in `Lotus::Loader`
  2. create `config/initializers/.gitkeep` for both the architectures (application and container)
  3. not fail if `config/initializers` is missing at all. This won't break apps that will upgrade from previous versions.

Thank you :+1:

**Comment by lucasallan** [comment]
@jodosha Yes, I can do it. I'll start it later today (it's morning here).

From now on, I'll start suggesting features on Friday evening! lol

Thanks!

**Comment by theocodes** [comment]
yay! :+1:  @lucasallan feel free to ask if you need any help :)

**Comment by jodosha** [comment]
@theocodes Please show up on gitter, I've another issue for you! :+1:
