### ISSUE TITLE
Could not find a valid gem 'lotus-utils'

### ISSUE THREAD

**Issue by noahc** [lotus/lotus#376]
I was looking for something simple just to make sure I had everything figured out. I noticed the Gemfile generates an extra space. So, I figured out what I thought would fix it and made that change. Now, I wanted to test it. 

Here's how I went about that:

```
 ~/Projects/lotus/noah-lotus gem build ./lotusrb.gemspec
WARNING:  description and summary are identical
WARNING:  pessimistic dependency on minispec-metadata (~> 3.2.1, development) may be overly strict
  if minispec-metadata is semantically versioned, use:
    add_development_dependency 'minispec-metadata', '~> 3.2', '>= 3.2.1'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: lotusrb
  Version: 0.5.0
  File: lotusrb-0.5.0.gem
~/Projects/lotus/noah-lotus gem install lotusrb-0.5.0.gem
ERROR:  Could not find a valid gem 'lotus-utils' (~> 0.6) in any repository
ERROR:  Possible alternatives: lotus-utils
```
Having never done this before, I thought that maybe I was doing something wrong. So, I pushed this branch up to Github and tried a different approach. I figured, I could add it to an exist Gemfile and do a `bundle install` and that would install the modified gem into my gemset. I could then select that and start a new lotus project which should test the Gemfile creation. 

It looks like this: 

```
source 'https://rubygems.org'

gem 'bundler'
gem 'rake'

gem 'lotusrb',     '0.5.0', git: "https://github.com/noahc/lotus.git", branch: "remove-extra-new-line-in-gem-file"
gem 'lotus-model', '~> 0.5'


gem 'pg'

group :test do 
  gem 'minitest'
  gem 'capybara'
end

group :production do 
  # gem 'puma'
end
```
and generates this error

```
 ~/Projects/lotus/bookshelf bundle install                                                                                                                                                                                
Fetching https://github.com/noahc/lotus.git
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "lotus-utils":
  In Gemfile:
    lotusrb (= 0.5.0) ruby depends on
      lotus-utils (~> 0.6) ruby
Could not find gem 'lotus-utils (~> 0.6) ruby', which is required by gem 'lotusrb (= 0.5.0) ruby', in any of the sources.
```
What am I doing wrong? I tried doing just `gem install lotus-utils` and re-running the bundle install. Still go the same error.

Additionally, would it be beneficial for me to add additional details to the contributors guide that walks them through setting this up the first time for their first contribution?

**Comment by jodosha** [comment]
@noahc Hello :smile: 

That version of `lotus-utils` wasn't released yet. The `master` branch here has to depend on it, because `lotusrb-0.6.0` will require `lotus-utils-0.6.0`.

To solve your problem, you can just amend your `Gemfile` with:

```ruby
#...
gem 'lotus-utils', github: 'lotus/utils'
```

In general just use `lotus new bookshelf --lotus-head=true`. It generates a `Gemfile` that looks like this:

```ruby
source 'https://rubygems.org'

gem 'bundler'
gem 'rake'

gem 'lotus-utils',       require: false, github: 'lotus/utils'
gem 'lotus-router',      require: false, github: 'lotus/router'
gem 'lotus-validations', require: false, github: 'lotus/validations'
gem 'lotus-helpers',     require: false, github: 'lotus/helpers'
gem 'lotus-controller',  require: false, github: 'lotus/controller'
gem 'lotus-view',        require: false, github: 'lotus/view'
gem 'lotus-model',       require: false, github: 'lotus/model'
gem 'lotus-mailer',      require: false, github: 'lotus/mailer'
gem 'lotusrb',                           github: 'lotus/lotus'


group :test do
  gem 'minitest'
  gem 'capybara'
end

group :production do
  # gem 'puma'
end
```



> Additionally, would it be beneficial for me to add additional details to the contributors guide that walks them through setting this up the first time for their first contribution?

Yes please :+1:
