### ISSUE TITLE
Could not generate new action for app which name contains underscore

### ISSUE THREAD

**Issue by joneslee85** [lotus/lotus#381]
**Step to reproduce**:
1) Generate new app with HEAD `lotus new --application=api_v1 demo --lotus-head`
2) Change into this app dir: `cd demo` and `bundle install`
3) Generate new action: `bundle exec lotus generate action api_v1 books#index`
4) Expected: No errors, Actual: Got errors

Seems to me a regression.

**Comment by jasoncharnes** [comment]
I'd be glad to give this a go tonight.

**Comment by joneslee85** [comment]
@jasoncharnes it's yours
