### ISSUE TITLE
CLI destroy application

### ISSUE THREAD

**Issue by thaod** [lotus/lotus#382]
Hi all,

I think having `lotus destroy application [application-name]` could be nice. Please help to consider it :).

**Comment by joneslee85** [comment]
I like this idea, please give it a go if you want

**Comment by lucasallan** [comment]
I could give it a go if you don't mind @thaod @joneslee85

**Comment by joneslee85** [comment]
@lucasallan please take it

**Comment by thaod** [comment]
Yes, please @lucasallan

**Comment by lucasallan** [comment]
I'll work on it soon - most likely end of this week.

**Comment by joneslee85** [comment]
ping @lucasallan

**Comment by lucasallan** [comment]
@joneslee85 I haven't had a chance to work on it yet, but I'll do asap.
