### ISSUE TITLE
lotus-model-cli

### ISSUE THREAD

**Issue by DanielBlanco** [lotus/lotus#386]
Hi I'm using https://github.com/lotus/model for a non-web application and I would love to have:

```
$ lotus generate model x
$ lotus generate migration create_x
```

And all the useful lotus cli commands that are specific to lotus-model.

Can we move these cli commands to lotus-model gem? or to a new lotus-model-cli gem?

**Comment by joneslee85** [comment]
@DanielBlanco lotus-model is designed to be framework-agnostic. We don't want to enforce a convention / rules on how lotus-model should be used.

You can look into the lotusrb generator code and copied CLI code to your app.

**Comment by jodosha** [comment]
@DanielBlanco I agree with @joneslee85 

Please remember that migrations don't need a timestamp, they are ran as they appear in the directory. That means, you can have progressive numbers as prefix.

Another facility is the `Lotus::Model.migration` block, that you can easily type when manually creating a migration.

**Comment by DanielBlanco** [comment]
@jodosha and @joneslee85 OK, thank you for the clarification! 

I ended up using the `Lotus::Model.migration` block with some custom `db:*` rake tasks.

**Comment by jodosha** [comment]
@DanielBlanco Sweet, thank you! :+1:
