### ISSUE TITLE
Enable recreation of database-configuration

### ISSUE THREAD

**Issue by florianb** [lotus/lotus#389]
When starting my first project with lotus i decided to omit the `--database`-switch. I would now like to configure the database-adapter.

Unfortunately there's no command to recreate the database-configuration nor there's a database-setup-mockup. But probably i missed something?

However - i would like to help, so if i could do anything to improve this point - even if it's only an improvement of the docs - give me a hint.

**Comment by jodosha** [comment]
@florianb Hello, I'm sorry for the hassle. I'm gonna explain the steps here, it would be really appreciated if you could create a PR for `lotus/lotus.github.io` repository to document it.

Let's say you have created a project with `lotus new bookshelf`, and you have a `Book` entity and its related repository.

You have to edit your `lib/bookshelf.rb` like this:

```ruby
  # Change :type to :sql
  adapter type: :sql, uri: ENV['BOOKSHELF_DATABASE_URL']

  # Specify settings for migrations
  migrations 'db/migrations'
  schema     'db/schema.sql'
```

Then edit related env var (`BOOKSHELF_DATABASE_URL`) into `.env.development` and `.env.test`.

Add database driver to your `Gemfile` (eg. `pg` or `mysql2` gems).

That's it!

**Comment by florianb** [comment]
Hi @jodosha,

thanks for your quick response - i'll create a PR. :100:
