### ISSUE TITLE
Asset path/url helpers

### ISSUE THREAD

**Issue by jodosha** [lotus/lotus#394]
Implement helpers for relative and absolute URL assets resolution.

### Usage

```erb
<ol>
  <li><%= asset_path('logo.png') %></li>
  <li><%= asset_url('logo.png') %></li>
</ol>
```

This produces

```html
<ol>
  <li>/assets/logo.png</li>
  <li>https://lotusrb.org/assets/logo.png</li>
</ol>
```

### URL Prefix

This should take account of the [`prefix`](https://github.com/lotus/assets/blob/master/lib/lotus/assets/configuration.rb#L45) defined in `Lotus::Assets::Configuration`.

That means, if an application has a prefix: `/admin`, when one of these helpers is used, the prefix should be used.

```erb
<div style="background-image: url('<%= asset_path('bg.png')) %>')">
</div>
```

Produces:

```html
<div style="background-image: url('/assets/admin/bg.png')">
</div>
```

### URL Settings

For absolute URLs (`asset_url`), it should respect the following settings from `Lotus::Configuration`:

  * `scheme`
  * `domain`
  * `port`

### Digest Mode

If "Digest Mode" is enabled (usually in production), it should generate the file name with the digest suffix (see https://github.com/lotus/assets/blob/master/lib/lotus/assets/configuration.rb#L37).

```erb
<div style="background-image: url('<%= asset_path('bg.png')) %>')">
</div>
```

Produces:

```html
<div style="background-image: url('/assets/bg-78a21a377046e9ddb3bd9b509c22d4c3.png')">
</div>
```

## Rendering Contexts

These two helpers that MUST be available in the following rendering contexts:

  * views
  * templates
  * assets
  * mailers

**Comment by florianb** [comment]
Hi @jodosha - i'd like to give it a try.

**Comment by joneslee85** [comment]
@florianb it's your now

**Comment by florianb** [comment]
Thanks @joneslee85!

I recently added test-mocks to my fork, but i have trouble accessing the `Lotus::Configuration` from within the assets. As far as i figured out, the `scheme`, `domain` and `port`-parameter reside in the `<<App-Name>>::Application.configuration`.

The `Lotus::Asset.configuration` provides only a subset of parameters and i have the feeling that it's probably not desired to extend the `Asset.configuration`.

I would be really thankful for a hint on what to depend on the best.

A second question i have is about the caching-mechanism:

I assume it is not desired to file-cache paths/urls as it is done with `tag`-snippets. But i think a caching mechanism (in memory) would probably a smart thing in the next-steps. Should i ignore the caching for now?

Thank you in advance!

**Comment by florianb** [comment]
The helpers will go into `lib/lotus/helpers/asset_url_helper.rb` and `asset_path_helper`.

Picking up jodosha's notes from Gitter:

We will need a new AssetHelperModule - f.e. `Web::Helpers::AssetTagHelpers`:

```
helpers = Module.new {
  def self.included(view)
    view.class_eval do
      class_accessor :asset_path_prefix
      self.asset_path_prefix = configuration.prefix

      include Lotus::Helpers::AssetTagHelpers
    end
  end
}

namespace.const_set('Helpers::AssetTagHelper', helpers)
```

The mixin is the reachable like that:

```
def asset_path(path)
  self.class.asset_path_prefix + path
end
```

It seems like that **all** asset-helpers then can safely rely on the `self.class.asset_path_prefix`-method.

**Comment by florianb** [comment]
Hi @jodosha,

i need help with a problem. Currently the unit-tests are running fine and i have a first implementation working. After putting the integration tests on i was faced with the following error.

Currently i mix the two methods in which make use of the configuration object like this:

1. i extract the current app-name and reassemble it to `Collaboration::Application` (in the test env)
2. i then access its configuration-object: `Collaboration::Application.configuration` (which is used for scheme, host and port)
3. at last i also access the assets-configuration like this: `Collaboration::Application.configuration.assets`

After the last step i get a weird object back - consisting somehow of an Array (`[:prefix, [], nil]`). I was not able to pin it down with pry.

I suppose that the `assets`-method at the point of accessing is not set properly, and my question is what is returned instead? It seems that i can't cleanly "or-set" the return value to `nil`.

Am i going to fetch the Configuration at the wrong point or is there something else going wrong?

I gisted the relevant information here: https://gist.github.com/florianb/f6c6c05997dbf257dfeb

Thanks in advance!

**Comment by florianb** [comment]
I added a question on Stackoverflow: http://stackoverflow.com/questions/34038428/method-call-in-repl-returns-weirdly-nothing

**Comment by jodosha** [comment]
Implemented by:

  * https://github.com/lotus/assets/pull/27
  * https://github.com/lotus/assets/pull/28
