### ISSUE TITLE
Exposures HTML-escaped too soon (?)

### ISSUE THREAD

**Issue by katafrakt** [lotus/lotus#398]
I'm not sure if it's good repository to report, but here is my use case:

In the controller, I'm fetching some web pages as HTML. I want to run it through readability gem and finally display in the template. Unfortunately, even if I make readability call in the view, it's too late. The string is already escaped and I have no way to render it properly. 

All I can do is:

```ruby
    expose :source_html

    def call(params)
      @source_html = ::Lotus::Utils::Escape::SafeString.new(open(params[:url]).read)
    end
````

Which is fine, but totally undocumented. Also, I'm not quite sure this is a formal public API to do that and if it won't change in the future.

So, one way would be to provide `_raw` helper which does the wrapping above, on controller level (it's not available right now). Another would be to describe this solution as recommended somewhere in the docs. One more would be to escape HTML between view and template, not between controller and view, although I understand it might be not desired for other security reasons.

**Comment by jodosha** [comment]
@katafrakt Hello and thanks for taking the time to report this. It's really appreciated.

Exposures aren't escaped in the action, [but in in the view](https://github.com/lotus/view/blob/6ab59b22351412ac0436dcb56e8d3ba6e9487d20/lib/lotus/view/rendering/scope.rb#L62-L72).

To solve your problem, add this method to your **view**:

```ruby
def source_html
  _raw locals[:source_html]
end
```

This will shadow the exposure coming from the action, and at the same time will prevent automatic escape to act on it.

PS: Please check your code in the action, [it's really insecure](http://sakurity.com/blog/2015/02/28/openuri.html) what you do with `open-uri`.

**Comment by katafrakt** [comment]
Great! That's exactly what I needed. Thank you for your help and pointing out the security risk! :wink:  

Is the shadowing documented somewhere and I missed it or should it be added (I can do it)?

**Comment by jodosha** [comment]
> Is the shadowing documented somewhere and I missed it or should it be added (I can do it)?

Not sure I've got the question. Sorry :weary:
