### ISSUE TITLE
Allow redirects with symbols

### ISSUE THREAD

**Issue by jodosha** [lotus/lotus#4]
As now we have two ways to specify an URL for a redirect in an action:

By hardcoding the path:
```ruby
redirect_to '/'
```

By using the helper:
```ruby
redirect_to MyApp::Routes.url(:root)
```

I would like to introduce a third way:
```ruby
redirect_to :root
```

**Comment by joneslee85** [comment]
@fuadsaud ping, any update?

**Comment by jodosha** [comment]
This opens an inconsistency with routing helpers in views. Not a good idea.
