### ISSUE TITLE
Favicon helper

### ISSUE THREAD

**Issue by jodosha** [lotus/lotus#400]
Implement `favicon` helper.

See `Lotus::Assets::Helpers` for reference.

### Basic Usage

```erb
<%= favicon %>
```

```html
<link href="/assets/favicon.ico" rel="shortcut icon" type="image/x-icon">
```

### Path

It also accepts an optional path

```erb
<%= favicon 'myfavicon.ico' %>
```

```html
<link href="/assets/myfavicon.ico" rel="shortcut icon" type="image/x-icon">
```

### URL Prefix

This should take account of the [`prefix`](https://github.com/lotus/assets/blob/master/lib/lotus/assets/configuration.rb#L45) defined in `Lotus::Assets::Configuration`.

That means, if an application has a prefix: `/admin`, when one this helper is used, the prefix should be used.

```erb
<%= favicon %>
```

```html
<link href="/assets/admin/favicon.ico" rel="shortcut icon" type="image/x-icon">
```

### Digest Mode

If "Digest Mode" is enabled (usually in production), it should generate the file name with the digest suffix (see https://github.com/lotus/assets/blob/master/lib/lotus/assets/configuration.rb#L37).

```erb
<%= favicon %>
```

```html
<link href="/assets/favicon-78a21a377046e9ddb3bd9b509c22d4c3.ico" rel="shortcut icon" type="image/x-icon">
```

## Testing Notes

Add an integration test with Lotus::View, in order to make sure that the output isn't escaped twice and produces a valid HTML.

**Comment by jasoncharnes** [comment]
I'd be glad to pick this one up.

**Comment by jodosha** [comment]
@jasoncharnes Please do.

**Comment by jasoncharnes** [comment]
I'm a little more tied up than I thought I would be. If someone else wants to take this, feel free. If not, I'll get to it as soon as my schedule opens.

**Comment by jodosha** [comment]
@jasoncharnes Sure, thank you.

**Comment by michaeldeol** [comment]
I would love to give this a shot!

**Comment by michaeldeol** [comment]
I have opened a PR #409.

One question I did have was with regards to mobile Safari. In the Rails world, `favicon_link_tag` allows for the passing of options `rel="apple-touch-icon"`. Is this something you would want to see happen in this helper or is the intent to keep it separate?

**Comment by joneslee85** [comment]
@deepj to avoid duplicating works, please ask before claiming the issue.

@michaeldeol I have merged #408, but I would love to get your integration in too, please update your PR with just the integration spec and I'll merge

**Comment by michaeldeol** [comment]
@joneslee85 done, just waiting on travis.

**Comment by deepj** [comment]
@joneslee85 Thanks for notice. I hadn't have the refreshed issue in a tab so I didn't notice @michaeldeol claim. I'm sorry for that.
