### ISSUE TITLE
`lotus serve` is not recognizing `configure :production`

### ISSUE THREAD

**Issue by florianb** [lotus/lotus#416]
When running my local lotus app (which is out of the box ~0.5.0) in `production` mode, the configuration-directive from the `application-rb` is not recognized.

As the console output shows (https://gist.github.com/florianb/1586758826d9b521f440) the server is starting in the production mode, but the whole network-configuration is invalid (`tcp://0.0.0.0:2300`).

**Comment by florianb** [comment]
Oh - and i should mention that this also happens if i'm using the Webrick-server.

**Comment by jodosha** [comment]
@florianb Does this happens with other servers (eg. Puma)?

**Comment by florianb** [comment]
@jodosha, @joneslee85 (thanks for the hint): I guess it's my fault - i used `RACK_ENV` to set the environment estimating that lotus will use it to deviate the `LOTUS_ENV`.

I guess the issue may be closed.

**Comment by jodosha** [comment]
@florianb That's interesting. `ENV['RACK_ENV']` should be [detected](https://github.com/lotus/lotus/blob/master/lib/lotus/environment.rb#L205) by `Lotus::Environment` as well.

What happens if you use `RACK_ENV=production bundle exec lotus server` and print these three lines from a template?

```erb
<%= ENV['RACK_ENV'] %>
<%= ENV['LOTUS_ENV'] %>
<%= Lotus.env?(:production) %>
```

**Comment by florianb** [comment]
@jodosha - the environment seems to be set properly:

```
- ENV['RACK_ENV']: production
- ENV['LOTUS_ENV']: production
- Lotus.env?(:production): true
```

Unfortunately all servers (Webrick & Puma) get bound to `0.0.0.0:2300` which is at least the wrong port, but also the wrong ip-address, since my `lib/test.rb:226` defines the following:

```
    ##
    # PRODUCTION
    #
    configure :production do
      scheme 'http'
      host   '127.0.0.1'
      port   8181
    end
```

**Comment by jodosha** [comment]
@florianb But this changes if you use `LOTUS_ENV=production`? I mean, that behaves correctly and uses the right scheme/host/port?

**Comment by florianb** [comment]
@jodosha: Thanks for explicitly asking - it doesn't. So probably the whole `configure`-block isn't recognized.

**Comment by jodosha** [comment]
@florianb This issue could have been fixed in master. I have an application that uses this repository head and successfully yields `production` block in development and production.

I use Puma on Heroku and this is my configuration:

```ruby
# Procfile
web: bundle exec puma -t ${PUMA_MIN_THREADS:-8}:${PUMA_MAX_THREADS:-12} -w ${PUMA_WORKERS:-2} -p $PORT -e ${LOTUS_ENV:-development}
# ...
```

I'm closing this for now, please reopen if 0.6 (released soonish) will not fix it.
