### ISSUE TITLE
LoadError: cannot load such file -- sequel/adapters/memory (Sequel::AdapterNotFound)

### ISSUE THREAD

**Issue by florianb** [lotus/lotus#417]
I tried to add database-support to a nearly new app (`my_project`) by following the points below:

1. Generating a Model (consisting of a Entity and a Repository)
2. Generating a Migration (implementing an `up` and `down`-directive)
3. Configuring an Adapter (at `lib/my_project.rb`)
4. Running a `bundle exec lotus db create`, to create a database

As this [Gist](https://gist.github.com/florianb/2e89b5e5f04aa4776529) shows, the sequel-adapter can't be loaded. The example shows a `memory`-adapter but it fails on `sql`-adapters as well.

**Comment by michaeldeol** [comment]
According to the Sequel gem docs, I don't see anything about a memory adapter. https://github.com/jeremyevans/sequel

>Sequel currently has adapters for ADO, Amalgalite, CUBRID, DataObjects, IBM_DB, JDBC, MySQL, Mysql2, ODBC, Oracle, PostgreSQL, SQLAnywhere, SQLite3, Swift, and TinyTDS.

Not sure why it would fail on the other adapters though.

**Comment by michaeldeol** [comment]
Just to follow up; Lotus::Model does in fact have a memory adapter: https://github.com/lotus/model/blob/master/lib/lotus/model/adapters/memory_adapter.rb.

I too run into this issue switching from `type: :sql` using postgres to `type: :memory`. Same for sqlite.

**Comment by AlfonsoUceda** [comment]
Hi @florianb this isn't bug, you are trying to connect mysql protocol with mysql2 gem, because Sequel has two adapters, `mysql` and `mysql2` you have to use the right protocol and gem.

we have to update this line https://github.com/lotus/lotus/blob/master/lib/lotus/generators/application/app/lib/app_name.rb.tt#L16 with `mysql2` protocol.

When you generate a new lotus app with mysql adapter, the mysql2 gem and procotol is used.

**Comment by michaeldeol** [comment]
Leaving a note here for anyone else. @AlfonsoUceda helped me find that the issue with the MySQL adapter not working is due to the incorrect protocol being used. I was using `mysql://` instead of `mysql2://`

Working Example Below:

```ruby
adapter type: :sql, uri: 'mysql2://localhost/appname_development'
```

**Comment by AlfonsoUceda** [comment]
@florianb @michaeldeol changed the line in the comment: https://github.com/lotus/lotus/commit/a30d8d5e2fbccca75e4c5b7e62f32a7f3d3d6f68

**Comment by jodosha** [comment]
@AlfonsoUceda @joneslee85 This should be fixed: `mysql` should work as expected.

It's unexpected to see it to not work. And why it shouldn't?
When devs aren't in control of the URL they can't use Lotus. Think of Heroku, IIRC they use `mysql://` scheme for `ENV['DATABASE_URL']` and devs can't change it.

Please fix it.
