### ISSUE TITLE
Add template options to new command

### ISSUE THREAD

**Issue by davydovanton** [lotus/lotus#430]
Hello,
I think it will be good to add `--template` options for `new` command. For example now we can realize only erb, slim and haml arguments.

If you're agree I can make real this feature in the near future :blush:

**Comment by jodosha** [comment]
@davydovanton That depends on `template` value in `.lotusrc`. If you change that value, into something like `slim`, it will generate templates like `show.html.slim`.

**Comment by davydovanton** [comment]
yes, I understood that. I propose to add the key to `lotus new` command which replace `template` value in `.lotusrc` file like `--test` key.

**Comment by jodosha** [comment]
@davydovanton Sorry, if I misread your suggestion. In my mind I read `new` as `generate` :sob: 

In the past we wanted to ship this feature, the main obstacle was to generate the `application.html.*` application template. That of course means to maintain a `.tt` file for each of the supported template engines and multiply for the architectures that we have (x2).

Now, this isn't impossible, but we need to make sure that both CLI and `application.html.erb` contents are stable before to add this feature.

---

Ref https://github.com/lotus/lotus/issues/155
Ref https://github.com/lotus/lotus/pull/379
