### ISSUE TITLE
Welcome page shows wrong app name when multiple apps are present

### ISSUE THREAD

**Issue by jodosha** [lotus/lotus#452]
Steps to reproduce:

```shell
➜ lotus new bookshelf && cd bookshelf && bundle
➜ bundle exec lotus generate app admin
➜ bundle exec lotus server
```

Visit [http://localhost:2300](http://localhost:2300).

It shows this screen:

![screen shot 2016-01-12 at 12 12 46](https://cloud.githubusercontent.com/assets/5089/12262097/dab403a2-b925-11e5-8bf2-8ac406e49a2b.png)

If you give a close look at the instructions they say:

```
bundle exec lotus generate action admin home#index --url=/
```

It reports `admin` instead of `web` as name.

**Comment by davydovanton** [comment]
Little help: error on [this line](https://github.com/lotus/lotus/blob/master/lib/lotus/welcome.rb#L29) :smile:

**Comment by jodosha** [comment]
We should probably introspect `env['PATH_INFO']` and decide the name of the application at the runtime.

Given two apps:

```ruby
# config/environment.rb
Lotus::Container.configure do
  mount Admin::Application, at: '/admin'
  mount Web::Application, at: '/'
end
```

For request `GET /`, we should show `"web"`, while for `GET /admin` we should pick `"admin"`.

Hint: `Application#path_prefix` can be useful to solve this problem.
