### ISSUE TITLE
Generate controller with all restful actions

### ISSUE THREAD

**Issue by davydovanton** [lotus/lotus#460]
Simetimes I want to generate controller with all restful actions (index, create, new, etc). What do you think? Will it helpful?

if you agree with this proposal, I'm ready to do it :)

**Comment by cllns** [comment]
I think @jodosha is pretty firmly against this. For the reasoning, see [Issue #385](https://github.com/lotus/lotus/issues/385#issuecomment-155102146).

**Comment by joneslee85** [comment]
@davydovanton this is like scaffold generator which @jodosha consider anti-pattern.

**Comment by jodosha** [comment]
@joneslee85 Thanks :+1:
