### ISSUE TITLE
JRuby support

### ISSUE THREAD

**Issue by PragTob** [lotus/lotus#71]
JRuby support is currently missing from lotus.

Asking @jodosha it seems to be because `Module.prepend` is missing in the current JRuby release.

FYI `Module.prepend` seems to be mostly implemented on JRuby master jruby/jruby#751 which is the next major release (JRuby 9k) - unfortunately I dunno when it's gonna land (hoping for start of next year personally).

If I get a lot of time I might look into the code to figure out if prepend could be reasonably replaced.

Cheers!

**Comment by joneslee85** [comment]
I created a feature card https://trello.com/c/aRmE8bSF/107-support-jruby

**Comment by jodosha** [comment]
@PragTob Do you use JRuby in production? Supporting multiple VMs is getting harder and harder for us. We're evaluating what to do.

**Comment by PragTob** [comment]
JRuby is used by multiple companies in production - here is a recent slide of companies using JRuby in production/for their applications:

![JRuby companies](https://pbs.twimg.com/media/B2rTTk0CMAAePLK.png:large)

Sadly I don't use it in production right now as I don't have an app that is "mine" deployed - but I'm a frequent JRuby promoter and just wait for a chance to plug it in :). And it is frequently recommended in settings where high performance/scalability is needed. High load companies like SoundCloud and TravisCI use it frequently (in the majority of their apps that use ruby, as far as I am aware). For instance this discussion on Ruby rogues: http://devchat.tv/ruby-rogues/162-rr-scaling-rails-with-steve-corona

Where is the pain with supporting JRuby? Can I help you there? 9k should release this year and be 2.2 compatible - the only stuff that I know is not supported is C extensions, but mostly there is an equivalent Java replacement or a `ffi` compatible gem :) Supporting 9k+ should be ok I believe.

So JRuby support is vital imo to the success of a web framework in today's ruby landscape.

Sorry time is kind of limited, balancing new job, shoes4, ruby user group berlin and confs - but would love to help with JRuby support in code as well. Always here for at least information support etc. :)

PS: As a full disclosure I'm biased towards JRuby of course, biased enoughso that people convinced me to organize JRubyconf this year :)

**Comment by jodosha** [comment]
@PragTob Thanks for the extensive explanation about the benefits of supporting JRuby.

Our problem time and effort. Our Core Team is made of two people, working on free time on Lotus. We have contributors who are helping **a lot** to speed things up.

Supporting several VMs with a different set of features is becoming a burden for us. Sadly, Ruby is what MRI is. Other implementations will eventually follow. To add injury to insult, roadmaps for those rubies are never clear.

If we plan a release, we can never tell if we should add workarounds for those VMs, or if they will come out with a new version that brings what we need.

We want to apply an 80/20 rule. For our sanity and to ensure that Lotus will make progress.

I'll give you one example: collectable symbols. This MRI 2.2 feature solves a lot of problems for us. To symbolize params representing untrusted input was a serious security threat. We put in place slow but safe mechanism to make Lotus defended against those attacks.

Again, this required and requires time and attention. This effort can be used to build other features, if we assume that the current VM will collect symbols and move on.

In less than a week we should have JRuby 9k beta released which will be compliant with MRI 2.2.

We don't have a timeline for Rubinius yet.

I'm closing this discussion, by saying that the next minor releases will only target VMs with 2.2+ mode.

**Comment by PragTob** [comment]
Would be nice to add to the README :). Targetting 2.2+ compatible VMS seems good with me :) Thanks!

**Comment by jodosha** [comment]
@PragTob Rubies compat is documented in all the READMEs. You don't see JRuby in `lotus/lotus` repo because both Model and Controller aren't compatible with it and so Lotus isn't.

**Comment by PragTob** [comment]
I was looking for "MRI 2.2+ compatible rubies" :) README says 2.0+

**Comment by jodosha** [comment]
@PragTob We want to wait a bit, then cleanup the code of the gems and bump a minor version of all of them. It's a decision that we just took. :)
