### ISSUE TITLE
Get response from middleware

### ISSUE THREAD

**Issue by Jesterovskiy** [lotus/lotus#82]
I used this construction:
``` ruby
action 'SignIn' do
  use Auth::SignIn

  def call(params)
  end
end
```
Auth::SignIn returns Rack::Response, but action SignIn doesn't know about this response. How can I return this response or get params from middleware to call method?

**Comment by AlfonsoUceda** [comment]
@Jesterovskiy this is solved with https://github.com/lotus/controller/pull/78 and https://github.com/lotus/router/pull/36 now you can access to response inside the middleware, an example:

```ruby
class MyMiddleware
  def initialize(app
    @app = app # app is the action, and in the action you can access to response https://github.com/lotus/controller/blob/master/lib/lotus/action/rack.rb#L138
  end

  def call(env)
    code, headers, body = @app.call(env)
    [code, headers, body]
  end
end

class MyAction
  use MyMiddleware

  def call(params)
  end
end
```

**Comment by Jesterovskiy** [comment]
@AlfonsoUceda thanks!
